In [1]:
label2num = {'1161364': 0, '116570': 1, '1176823': 2, '1595929': 3, '209233': 4, '22930': 5, '22956': 6, '22961': 7, '22967': 8, '22973': 9, '22983': 10, '22985': 11, '23150': 12, '23154': 13, '23158': 14, '23176': 15, '23724': 16, '24279': 17, '24285': 18, '24287': 19, '24321': 20, '244024': 21, '25092': 22, '25214': 23, '326272': 24, '41970': 25, '43435': 26, '47144': 27, '476521': 28, '516975': 29, '555123': 30, '555145': 31, '555146': 32, '64898': 33, '65377': 34, '65380': 35, '66971': 36, '67107': 37, '67252': 38, '70711': 39, '738183': 40, '74113': 41, '74580': 42, '760266': 43, 'ashgre1': 44, 'astcra1': 45, 'bafcur1': 46, 'baffal1': 47, 'banana': 48, 'barant1': 49, 'batbel1': 50, 'baymac': 51, 'bbwduc': 52, 'bcwfin2': 53, 'bkcdon': 54, 'bkhpar': 55, 'blchaw1': 56, 'blheag1': 57, 'blttit1': 58, 'bncfly': 59, 'bobfly1': 60, 'brcmar1': 61, 'brnowl': 62, 'bucmot4': 63, 'bucpar': 64, 'bufpar': 65, 'bunibi1': 66, 'burowl': 67, 'camfli1': 68, 'chacha1': 69, 'chbmoc1': 70, 'chobla1': 71, 'chvcon1': 72, 'cibspi1': 73, 'coffal1': 74, 'compau': 75, 'compot1': 76, 'crbthr1': 77, 'crebec1': 78, 'dwatin1': 79, 'epaori4': 80, 'eulfly1': 81, 'fabwre1': 82, 'fepowl': 83, 'ficman1': 84, 'flawar1': 85, 'fotfly': 86, 'fusfly1': 87, 'gilhum1': 88, 'giwrai1': 89, 'glteme1': 90, 'grasal3': 91, 'greani1': 92, 'greant1': 93, 'greela': 94, 'grekis': 95, 'grepot1': 96, 'gretho2': 97, 'greyel': 98, 'grfdov1': 99, 'grhtan1': 100, 'gycwor1': 101, 'horscr1': 102, 'houspa': 103, 'hyamac1': 104, 'larela1': 105, 'lesela1': 106, 'lesgrf1': 107, 'limpki': 108, 'linwoo1': 109, 'litcuc2': 110, 'litnig1': 111, 'mabpar': 112, 'magant1': 113, 'magtan2': 114, 'masgna1': 115, 'nacnig1': 116, 'ocecra1': 117, 'oliwoo1': 118, 'orbtro3': 119, 'orwpar': 120, 'osprey': 121, 'pabspi1': 122, 'palhor3': 123, 'paltan1': 124, 'phecuc1': 125, 'picpig2': 126, 'pirfly1': 127, 'plasla1': 128, 'platyr1': 129, 'plcjay1': 130, 'pluibi1': 131, 'purjay1': 132, 'pvttyr1': 133, 'ragmac1': 134, 'rebscy1': 135, 'recfin1': 136, 'redjun': 137, 'relser1': 138, 'rinkin1': 139, 'rivwar1': 140, 'roahaw': 141, 'rubthr1': 142, 'rufcac2': 143, 'rufcas2': 144, 'rufgna3': 145, 'rufhor2': 146, 'rufnig1': 147, 'ruftho1': 148, 'ruftof1': 149, 'rumfly1': 150, 'ruther1': 151, 'rutjac1': 152, 'sabspa1': 153, 'saffin': 154, 'saytan1': 155, 'scadov1': 156, 'schpar1': 157, 'scther1': 158, 'shcfly1': 159, 'shshaw': 160, 'shtnig1': 161, 'sibtan2': 162, 'smbani': 163, 'smbtin1': 164, 'sobcac1': 165, 'sobtyr1': 166, 'socfly1': 167, 'sofspi1': 168, 'souant1': 169, 'soulap1': 170, 'souscr1': 171, 'spbant3': 172, 'spispi1': 173, 'sptnig1': 174, 'squcuc1': 175, 'stbwoo2': 176, 'strcuc1': 177, 'strher2': 178, 'strowl1': 179, 'swthum1': 180, 'swtman1': 181, 'tattin1': 182, 'thlwre1': 183, 'toctou1': 184, 'trokin': 185, 'trsowl': 186, 'undtin1': 187, 'varant1': 188, 'watjac1': 189, 'wesfie1': 190, 'wfwduc1': 191, 'whbant2': 192, 'whbwar2': 193, 'whiwoo1': 194, 'whlspi1': 195, 'whnjay1': 196, 'whtdov': 197, 'whwpic1': 198, 'y00678': 199, 'yebcar': 200, 'yebela1': 201, 'yecmac': 202, 'yecpar': 203, 'yehcar1': 204, 'yeofly1': 205, '1491113': 206, '25073': 207, '47158son01': 208, '47158son02': 209, '47158son03': 210, '47158son04': 211, '47158son05': 212, '47158son06': 213, '47158son07': 214, '47158son08': 215, '47158son09': 216, '47158son10': 217, '47158son11': 218, '47158son12': 219, '47158son13': 220, '47158son14': 221, '47158son15': 222, '47158son16': 223, '47158son17': 224, '47158son18': 225, '47158son19': 226, '47158son20': 227, '47158son21': 228, '47158son22': 229, '47158son23': 230, '47158son24': 231, '47158son25': 232, '517063': 233}
class_idx_mapping = {'Insecta': [0, 21, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 43], 'Reptilia': [1], 'Amphibia': [2, 206, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 207, 22, 23, 24, 28, 233, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], 'Mammalia': [4, 25, 26, 27, 29, 40, 41, 42], 'Aves': [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205]}

In [2]:
_FILE_MAP = {'stbwoo2/XC467895.ogg': 'stbwoo2-XC467895.mp3', '1161364/iNat1264238.ogg': '1161364-iNat1264238.mp3', '209233/iNat1545859.ogg': '209233-iNat1545859.m4a', '22956/iNat1693371.ogg': '22956-iNat1693371.m4a', '22973/iNat781822.ogg': '22973-iNat781822.m4a', '22973/iNat1353836.ogg': '22973-iNat1353836.mp3', '22973/iNat1460521.ogg': '22973-iNat1460521.mpga', '22973/iNat1645288.ogg': '22973-iNat1645288.mp3', '23158/iNat1322093.ogg': '23158-iNat1322093.m4a', '24279/iNat1306335.ogg': '24279-iNat1306335.m4a', '24279/iNat1435402.ogg': '24279-iNat1435402.mp3', '244024/iNat1219059.ogg': '244024-iNat1219059.m4a', '244024/iNat1583846.ogg': '244024-iNat1583846.m4a', '244024/iNat1573678.ogg': '244024-iNat1573678.m4a', '25092/iNat1645314.ogg': '25092-iNat1645314.m4a', '326272/iNat1299066.ogg': '326272-iNat1299066.m4a', '326272/iNat1303382.ogg': '326272-iNat1303382.m4a', '43435/iNat1054872.ogg': '43435-iNat1054872.mp3', '43435/iNat1243480.ogg': '43435-iNat1243480.mpga', '47144/iNat1717935.ogg': '47144-iNat1717935.m4a', '47144/iNat1346356.ogg': '47144-iNat1346356.m4a', '47144/iNat1346365.ogg': '47144-iNat1346365.m4a', '47144/iNat1317366.ogg': '47144-iNat1317366.m4a', '47144/iNat1559514.ogg': '47144-iNat1559514.m4a', '47144/iNat1191939.ogg': '47144-iNat1191939.mpga', '476521/iNat1648597.ogg': '476521-iNat1648597.m4a', '555146/iNat1375734.ogg': '555146-iNat1375734.m4a', '555146/iNat1375753.ogg': '555146-iNat1375753.m4a', '65377/iNat1372639.ogg': '65377-iNat1372639.m4a', '65377/iNat924044.ogg': '65377-iNat924044.mp3', '65377/iNat924035.ogg': '65377-iNat924035.mp3', '65377/iNat1676955.ogg': '65377-iNat1676955.m4a', '67107/iNat1635719.ogg': '67107-iNat1635719.m4a', 'ashgre1/iNat963674.ogg': 'ashgre1-iNat963674.m4a', 'ashgre1/iNat1400791.ogg': 'ashgre1-iNat1400791.m4a', 'baffal1/iNat1672327.ogg': 'baffal1-iNat1672327.m4a', 'baffal1/iNat1711622.ogg': 'baffal1-iNat1711622.m4a', 'banana/iNat1638891.ogg': 'banana-iNat1638891.m4a', 'banana/iNat1302882.ogg': 'banana-iNat1302882.m4a', 'banana/iNat1371833.ogg': 'banana-iNat1371833.m4a', 'banana/iNat335243.ogg': 'banana-iNat335243.m4a', 'banana/iNat1631602.ogg': 'banana-iNat1631602.m4a', 'banana/iNat1496209.ogg': 'banana-iNat1496209.m4a', 'banana/iNat1630115.ogg': 'banana-iNat1630115.m4a', 'barant1/iNat1654575.ogg': 'barant1-iNat1654575.m4a', 'barant1/iNat1418545.ogg': 'barant1-iNat1418545.m4a', 'barant1/iNat1738725.ogg': 'barant1-iNat1738725.m4a', 'barant1/iNat76423.ogg': 'barant1-iNat76423.mpga', 'batbel1/iNat851301.ogg': 'batbel1-iNat851301.mp3', 'batbel1/iNat851302.ogg': 'batbel1-iNat851302.mp3', 'batbel1/iNat851299.ogg': 'batbel1-iNat851299.mp3', 'batbel1/iNat1275000.ogg': 'batbel1-iNat1275000.m4a', 'batbel1/iNat1517987.ogg': 'batbel1-iNat1517987.m4a', 'batbel1/iNat1710152.ogg': 'batbel1-iNat1710152.m4a', 'baymac/iNat1304419.ogg': 'baymac-iNat1304419.m4a', 'baymac/iNat976078.ogg': 'baymac-iNat976078.m4a', 'bbwduc/iNat1318531.ogg': 'bbwduc-iNat1318531.m4a', 'bbwduc/iNat942901.ogg': 'bbwduc-iNat942901.m4a', 'bbwduc/iNat1294916.ogg': 'bbwduc-iNat1294916.m4a', 'bbwduc/iNat1338852.ogg': 'bbwduc-iNat1338852.m4a', 'bbwduc/iNat1499546.ogg': 'bbwduc-iNat1499546.m4a', 'bbwduc/iNat1352566.ogg': 'bbwduc-iNat1352566.m4a', 'bbwduc/iNat1543298.ogg': 'bbwduc-iNat1543298.m4a', 'bbwduc/iNat1683874.ogg': 'bbwduc-iNat1683874.m4a', 'bbwduc/iNat1580446.ogg': 'bbwduc-iNat1580446.m4a', 'bbwduc/iNat418728.ogg': 'bbwduc-iNat418728.m4a', 'bbwduc/iNat797291.ogg': 'bbwduc-iNat797291.m4a', 'bbwduc/iNat950353.ogg': 'bbwduc-iNat950353.m4a', 'bbwduc/iNat1333153.ogg': 'bbwduc-iNat1333153.m4a', 'bbwduc/iNat594163.ogg': 'bbwduc-iNat594163.m4a', 'bbwduc/iNat1520789.ogg': 'bbwduc-iNat1520789.m4a', 'bbwduc/iNat1705504.ogg': 'bbwduc-iNat1705504.m4a', 'bkcdon/iNat1637377.ogg': 'bkcdon-iNat1637377.m4a', 'bkcdon/iNat1396398.ogg': 'bkcdon-iNat1396398.m4a', 'bkhpar/iNat1637590.ogg': 'bkhpar-iNat1637590.m4a', 'bkhpar/iNat1029272.ogg': 'bkhpar-iNat1029272.m4a', 'blheag1/iNat1675853.ogg': 'blheag1-iNat1675853.mp3', 'blheag1/iNat953708.ogg': 'blheag1-iNat953708.m4a', 'bncfly/iNat1422961.ogg': 'bncfly-iNat1422961.m4a', 'bncfly/iNat1406256.ogg': 'bncfly-iNat1406256.m4a', 'bncfly/iNat1457501.ogg': 'bncfly-iNat1457501.m4a', 'bncfly/iNat1554596.ogg': 'bncfly-iNat1554596.mp3', 'bobfly1/iNat1691483.ogg': 'bobfly1-iNat1691483.m4a', 'bobfly1/iNat1200017.ogg': 'bobfly1-iNat1200017.mpga', 'bobfly1/iNat1556528.ogg': 'bobfly1-iNat1556528.m4a', 'bobfly1/iNat1487398.ogg': 'bobfly1-iNat1487398.m4a', 'brcmar1/iNat1730049.ogg': 'brcmar1-iNat1730049.m4a', 'brcmar1/iNat1658256.ogg': 'brcmar1-iNat1658256.m4a', 'brcmar1/iNat1737157.ogg': 'brcmar1-iNat1737157.m4a', 'brnowl/iNat1480534.ogg': 'brnowl-iNat1480534.m4a', 'brnowl/iNat1706506.ogg': 'brnowl-iNat1706506.mp3', 'brnowl/iNat1610861.ogg': 'brnowl-iNat1610861.m4a', 'brnowl/iNat514729.ogg': 'brnowl-iNat514729.m4a', 'brnowl/iNat1491227.ogg': 'brnowl-iNat1491227.m4a', 'brnowl/iNat1659173.ogg': 'brnowl-iNat1659173.m4a', 'brnowl/iNat1309637.ogg': 'brnowl-iNat1309637.m4a', 'brnowl/iNat1548013.ogg': 'brnowl-iNat1548013.m4a', 'brnowl/iNat1050844.ogg': 'brnowl-iNat1050844.m4a', 'brnowl/iNat1491232.ogg': 'brnowl-iNat1491232.m4a', 'bufpar/iNat1295642.ogg': 'bufpar-iNat1295642.mp3', 'bufpar/iNat1299514.ogg': 'bufpar-iNat1299514.m4a', 'burowl/iNat1589934.ogg': 'burowl-iNat1589934.m4a', 'camfli1/iNat1336230.ogg': 'camfli1-iNat1336230.m4a', 'chobla1/iNat228765.ogg': 'chobla1-iNat228765.m4a', 'chobla1/iNat1428711.ogg': 'chobla1-iNat1428711.m4a', 'chobla1/iNat1424302.ogg': 'chobla1-iNat1424302.m4a', 'chobla1/iNat1540294.ogg': 'chobla1-iNat1540294.m4a', 'coffal1/iNat1710475.ogg': 'coffal1-iNat1710475.m4a', 'coffal1/iNat782270.ogg': 'coffal1-iNat782270.m4a', 'coffal1/iNat905814.ogg': 'coffal1-iNat905814.m4a', 'coffal1/iNat826415.ogg': 'coffal1-iNat826415.m4a', 'coffal1/iNat1167591.ogg': 'coffal1-iNat1167591.m4a', 'coffal1/iNat1637929.ogg': 'coffal1-iNat1637929.m4a', 'coffal1/iNat782291.ogg': 'coffal1-iNat782291.m4a', 'coffal1/iNat395438.ogg': 'coffal1-iNat395438.m4a', 'compau/iNat1591339.ogg': 'compau-iNat1591339.m4a', 'compau/iNat946279.ogg': 'compau-iNat946279.m4a', 'compau/iNat1599244.ogg': 'compau-iNat1599244.m4a', 'compau/iNat1672503.ogg': 'compau-iNat1672503.m4a', 'compau/iNat1268738.ogg': 'compau-iNat1268738.m4a', 'compau/iNat1623767.ogg': 'compau-iNat1623767.m4a', 'compau/iNat1321681.ogg': 'compau-iNat1321681.m4a', 'compau/iNat1294212.ogg': 'compau-iNat1294212.m4a', 'compot1/iNat1668960.ogg': 'compot1-iNat1668960.m4a', 'compot1/iNat1660624.ogg': 'compot1-iNat1660624.m4a', 'crbthr1/iNat1693777.ogg': 'crbthr1-iNat1693777.m4a', 'crbthr1/iNat1684518.ogg': 'crbthr1-iNat1684518.m4a', 'crbthr1/iNat1678524.ogg': 'crbthr1-iNat1678524.m4a', 'crbthr1/iNat1277382.ogg': 'crbthr1-iNat1277382.m4a', 'epaori4/iNat1592245.ogg': 'epaori4-iNat1592245.m4a', 'epaori4/iNat649978.ogg': 'epaori4-iNat649978.m4a', 'eulfly1/iNat1738901.ogg': 'eulfly1-iNat1738901.m4a', 'fepowl/iNat1711295.ogg': 'fepowl-iNat1711295.m4a', 'fepowl/iNat1664968.ogg': 'fepowl-iNat1664968.m4a', 'fepowl/iNat1308138.ogg': 'fepowl-iNat1308138.m4a', 'fepowl/iNat1738605.ogg': 'fepowl-iNat1738605.m4a', 'fepowl/iNat1240485.ogg': 'fepowl-iNat1240485.mpga', 'fepowl/iNat1335628.ogg': 'fepowl-iNat1335628.m4a', 'fepowl/iNat1287848.ogg': 'fepowl-iNat1287848.mp3', 'fotfly/iNat1193130.ogg': 'fotfly-iNat1193130.m4a', 'fusfly1/iNat1518620.ogg': 'fusfly1-iNat1518620.m4a', 'giwrai1/iNat1673888.ogg': 'giwrai1-iNat1673888.m4a', 'giwrai1/iNat1349850.ogg': 'giwrai1-iNat1349850.m4a', 'grasal3/iNat1632581.ogg': 'grasal3-iNat1632581.mp3', 'grasal3/iNat1644284.ogg': 'grasal3-iNat1644284.m4a', 'grasal3/iNat1614411.ogg': 'grasal3-iNat1614411.m4a', 'greant1/iNat1635481.ogg': 'greant1-iNat1635481.m4a', 'greant1/iNat1508328.ogg': 'greant1-iNat1508328.m4a', 'greant1/iNat936816.ogg': 'greant1-iNat936816.mp3', 'greela/iNat1231355.ogg': 'greela-iNat1231355.m4a', 'grekis/iNat1690035.ogg': 'grekis-iNat1690035.m4a', 'grekis/iNat1572002.ogg': 'grekis-iNat1572002.m4a', 'grekis/iNat1209312.ogg': 'grekis-iNat1209312.mpga', 'grekis/iNat1663561.ogg': 'grekis-iNat1663561.m4a', 'grekis/iNat1400476.ogg': 'grekis-iNat1400476.m4a', 'grekis/iNat1623199.ogg': 'grekis-iNat1623199.mp3', 'grekis/iNat1391832.ogg': 'grekis-iNat1391832.m4a', 'grekis/iNat1667823.ogg': 'grekis-iNat1667823.mp3', 'greyel/iNat1381842.ogg': 'greyel-iNat1381842.m4a', 'greyel/iNat1375792.ogg': 'greyel-iNat1375792.m4a', 'greyel/iNat1375793.ogg': 'greyel-iNat1375793.m4a', 'greyel/iNat1350689.ogg': 'greyel-iNat1350689.m4a', 'greyel/iNat1370909.ogg': 'greyel-iNat1370909.m4a', 'greyel/iNat1638552.ogg': 'greyel-iNat1638552.m4a', 'greyel/iNat952416.ogg': 'greyel-iNat952416.m4a', 'greyel/iNat1350614.ogg': 'greyel-iNat1350614.m4a', 'greyel/iNat1303954.ogg': 'greyel-iNat1303954.m4a', 'grfdov1/iNat1395710.ogg': 'grfdov1-iNat1395710.m4a', 'grfdov1/iNat1400824.ogg': 'grfdov1-iNat1400824.m4a', 'gycwor1/iNat1537449.ogg': 'gycwor1-iNat1537449.m4a', 'gycwor1/iNat1288203.ogg': 'gycwor1-iNat1288203.m4a', 'gycwor1/iNat1596768.ogg': 'gycwor1-iNat1596768.m4a', 'gycwor1/iNat816375.ogg': 'gycwor1-iNat816375.mp3', 'gycwor1/iNat1255088.ogg': 'gycwor1-iNat1255088.m4a', 'gycwor1/iNat1594836.ogg': 'gycwor1-iNat1594836.m4a', 'gycwor1/iNat1378299.ogg': 'gycwor1-iNat1378299.mp3', 'gycwor1/iNat1346486.ogg': 'gycwor1-iNat1346486.m4a', 'gycwor1/iNat1620374.ogg': 'gycwor1-iNat1620374.m4a', 'gycwor1/iNat1569899.ogg': 'gycwor1-iNat1569899.m4a', 'gycwor1/iNat1624903.ogg': 'gycwor1-iNat1624903.m4a', 'gycwor1/iNat1577300.ogg': 'gycwor1-iNat1577300.m4a', 'gycwor1/iNat1724472.ogg': 'gycwor1-iNat1724472.m4a', 'gycwor1/iNat1683695.ogg': 'gycwor1-iNat1683695.m4a', 'houspa/iNat1666148.ogg': 'houspa-iNat1666148.m4a', 'houspa/iNat1409352.ogg': 'houspa-iNat1409352.m4a', 'houspa/iNat1364301.ogg': 'houspa-iNat1364301.mp3', 'houspa/iNat1551547.ogg': 'houspa-iNat1551547.m4a', 'houspa/iNat935753.ogg': 'houspa-iNat935753.m4a', 'houspa/iNat1397767.ogg': 'houspa-iNat1397767.m4a', 'houspa/iNat1512573.ogg': 'houspa-iNat1512573.m4a', 'houspa/iNat1362595.ogg': 'houspa-iNat1362595.m4a', 'houspa/iNat1417357.ogg': 'houspa-iNat1417357.m4a', 'houspa/iNat1321989.ogg': 'houspa-iNat1321989.m4a', 'houspa/iNat409684.ogg': 'houspa-iNat409684.m4a', 'houspa/iNat1304457.ogg': 'houspa-iNat1304457.m4a', 'houspa/iNat1569993.ogg': 'houspa-iNat1569993.m4a', 'houspa/iNat1731791.ogg': 'houspa-iNat1731791.m4a', 'houspa/iNat1316764.ogg': 'houspa-iNat1316764.m4a', 'houspa/iNat1358970.ogg': 'houspa-iNat1358970.m4a', 'limpki/iNat1319758.ogg': 'limpki-iNat1319758.m4a', 'limpki/iNat1320813.ogg': 'limpki-iNat1320813.m4a', 'limpki/iNat1072786.ogg': 'limpki-iNat1072786.m4a', 'linwoo1/iNat1302630.ogg': 'linwoo1-iNat1302630.m4a', 'linwoo1/iNat1535721.ogg': 'linwoo1-iNat1535721.m4a', 'linwoo1/iNat1371736.ogg': 'linwoo1-iNat1371736.m4a', 'mabpar/iNat1626097.ogg': 'mabpar-iNat1626097.m4a', 'masgna1/iNat1635487.ogg': 'masgna1-iNat1635487.m4a', 'oliwoo1/iNat1346713.ogg': 'oliwoo1-iNat1346713.m4a', 'orwpar/iNat1687083.ogg': 'orwpar-iNat1687083.m4a', 'orwpar/iNat1355177.ogg': 'orwpar-iNat1355177.m4a', 'orwpar/iNat1503877.ogg': 'orwpar-iNat1503877.m4a', 'orwpar/iNat1657675.ogg': 'orwpar-iNat1657675.mp3', 'orwpar/iNat1079708.ogg': 'orwpar-iNat1079708.m4a', 'osprey/iNat226664.ogg': 'osprey-iNat226664.m4a', 'osprey/iNat1398129.ogg': 'osprey-iNat1398129.m4a', 'osprey/iNat1595562.ogg': 'osprey-iNat1595562.m4a', 'osprey/iNat1370949.ogg': 'osprey-iNat1370949.m4a', 'osprey/iNat1692289.ogg': 'osprey-iNat1692289.m4a', 'osprey/iNat1556374.ogg': 'osprey-iNat1556374.m4a', 'osprey/iNat1004549.ogg': 'osprey-iNat1004549.m4a', 'osprey/iNat1670343.ogg': 'osprey-iNat1670343.m4a', 'osprey/iNat288776.ogg': 'osprey-iNat288776.m4a', 'osprey/iNat482127.ogg': 'osprey-iNat482127.m4a', 'osprey/iNat1135797.ogg': 'osprey-iNat1135797.m4a', 'osprey/iNat1697529.ogg': 'osprey-iNat1697529.m4a', 'osprey/iNat1359848.ogg': 'osprey-iNat1359848.m4a', 'osprey/iNat1361039.ogg': 'osprey-iNat1361039.m4a', 'paltan1/iNat1709147.ogg': 'paltan1-iNat1709147.m4a', 'paltan1/iNat1418628.ogg': 'paltan1-iNat1418628.m4a', 'paltan1/iNat1418634.ogg': 'paltan1-iNat1418634.m4a', 'paltan1/iNat1618415.ogg': 'paltan1-iNat1618415.m4a', 'picpig2/iNat1607749.ogg': 'picpig2-iNat1607749.m4a', 'pirfly1/iNat1635054.ogg': 'pirfly1-iNat1635054.m4a', 'pirfly1/iNat1677277.ogg': 'pirfly1-iNat1677277.m4a', 'plcjay1/iNat911601.ogg': 'plcjay1-iNat911601.mp3', 'plcjay1/iNat1612345.ogg': 'plcjay1-iNat1612345.m4a', 'plcjay1/iNat1435256.ogg': 'plcjay1-iNat1435256.m4a', 'plcjay1/iNat1435257.ogg': 'plcjay1-iNat1435257.m4a', 'rebscy1/iNat1324031.ogg': 'rebscy1-iNat1324031.m4a', 'redjun/iNat1661079.ogg': 'redjun-iNat1661079.m4a', 'redjun/iNat1681112.ogg': 'redjun-iNat1681112.m4a', 'redjun/iNat953958.ogg': 'redjun-iNat953958.m4a', 'relser1/iNat1557442.ogg': 'relser1-iNat1557442.m4a', 'relser1/iNat1370757.ogg': 'relser1-iNat1370757.m4a', 'relser1/iNat1344314.ogg': 'relser1-iNat1344314.mp3', 'roahaw/iNat1677378.ogg': 'roahaw-iNat1677378.m4a', 'roahaw/iNat1458636.ogg': 'roahaw-iNat1458636.mp3', 'rubthr1/iNat870811.ogg': 'rubthr1-iNat870811.mpga', 'rubthr1/iNat1684073.ogg': 'rubthr1-iNat1684073.m4a', 'rubthr1/iNat852442.ogg': 'rubthr1-iNat852442.mp3', 'rubthr1/iNat1682587.ogg': 'rubthr1-iNat1682587.mp3', 'rubthr1/iNat1672514.ogg': 'rubthr1-iNat1672514.m4a', 'rubthr1/iNat546228.ogg': 'rubthr1-iNat546228.m4a', 'rubthr1/iNat850316.ogg': 'rubthr1-iNat850316.mp3', 'rubthr1/iNat1707784.ogg': 'rubthr1-iNat1707784.mp3', 'rubthr1/iNat1615216.ogg': 'rubthr1-iNat1615216.mp3', 'rubthr1/iNat851551.ogg': 'rubthr1-iNat851551.mp3', 'rubthr1/iNat1691551.ogg': 'rubthr1-iNat1691551.m4a', 'rubthr1/iNat1691430.ogg': 'rubthr1-iNat1691430.m4a', 'rufnig1/iNat1657250.ogg': 'rufnig1-iNat1657250.m4a', 'rumfly1/iNat1734627.ogg': 'rumfly1-iNat1734627.m4a', 'ruther1/iNat1483642.ogg': 'ruther1-iNat1483642.mp3', 'saffin/iNat1692175.ogg': 'saffin-iNat1692175.m4a', 'saffin/iNat1313823.ogg': 'saffin-iNat1313823.m4a', 'saffin/iNat1300076.ogg': 'saffin-iNat1300076.m4a', 'saffin/iNat1300148.ogg': 'saffin-iNat1300148.m4a', 'saffin/iNat1667770.ogg': 'saffin-iNat1667770.mp3', 'saffin/iNat1449859.ogg': 'saffin-iNat1449859.m4a', 'saytan1/iNat1677185.ogg': 'saytan1-iNat1677185.m4a', 'scadov1/iNat1299298.ogg': 'scadov1-iNat1299298.m4a', 'scadov1/iNat1491465.ogg': 'scadov1-iNat1491465.m4a', 'scadov1/iNat1276971.ogg': 'scadov1-iNat1276971.m4a', 'schpar1/iNat1293642.ogg': 'schpar1-iNat1293642.m4a', 'shcfly1/iNat1321023.ogg': 'shcfly1-iNat1321023.m4a', 'shcfly1/iNat1532661.ogg': 'shcfly1-iNat1532661.m4a', 'shcfly1/iNat1345739.ogg': 'shcfly1-iNat1345739.m4a', 'shcfly1/iNat1471076.ogg': 'shcfly1-iNat1471076.m4a', 'shshaw/iNat1590156.ogg': 'shshaw-iNat1590156.m4a', 'shshaw/iNat1602640.ogg': 'shshaw-iNat1602640.m4a', 'shtnig1/iNat869228.ogg': 'shtnig1-iNat869228.mp3', 'shtnig1/iNat870997.ogg': 'shtnig1-iNat870997.mpga', 'shtnig1/iNat870998.ogg': 'shtnig1-iNat870998.mpga', 'shtnig1/iNat1696713.ogg': 'shtnig1-iNat1696713.m4a', 'sibtan2/iNat1402979.ogg': 'sibtan2-iNat1402979.m4a', 'smbani/iNat915724.ogg': 'smbani-iNat915724.m4a', 'smbani/iNat1594767.ogg': 'smbani-iNat1594767.m4a', 'smbtin1/iNat1734628.ogg': 'smbtin1-iNat1734628.m4a', 'smbtin1/iNat81751.ogg': 'smbtin1-iNat81751.mpga', 'sobcac1/iNat1387094.ogg': 'sobcac1-iNat1387094.m4a', 'sobcac1/iNat1432132.ogg': 'sobcac1-iNat1432132.m4a', 'sobtyr1/iNat1718955.ogg': 'sobtyr1-iNat1718955.m4a', 'sobtyr1/iNat1355327.ogg': 'sobtyr1-iNat1355327.m4a', 'socfly1/iNat1701203.ogg': 'socfly1-iNat1701203.m4a', 'socfly1/iNat1685298.ogg': 'socfly1-iNat1685298.m4a', 'socfly1/iNat1705430.ogg': 'socfly1-iNat1705430.m4a', 'socfly1/iNat1687317.ogg': 'socfly1-iNat1687317.m4a', 'socfly1/iNat1181651.ogg': 'socfly1-iNat1181651.m4a', 'socfly1/iNat671916.ogg': 'socfly1-iNat671916.m4a', 'socfly1/iNat797558.ogg': 'socfly1-iNat797558.mpga', 'sofspi1/iNat1664377.ogg': 'sofspi1-iNat1664377.mp3', 'sofspi1/iNat1510202.ogg': 'sofspi1-iNat1510202.m4a', 'soulap1/iNat1203529.ogg': 'soulap1-iNat1203529.mpga', 'soulap1/iNat1405995.ogg': 'soulap1-iNat1405995.m4a', 'soulap1/iNat1637171.ogg': 'soulap1-iNat1637171.m4a', 'soulap1/iNat1637169.ogg': 'soulap1-iNat1637169.m4a', 'soulap1/iNat1685486.ogg': 'soulap1-iNat1685486.m4a', 'soulap1/iNat1434604.ogg': 'soulap1-iNat1434604.mp3', 'souscr1/iNat1244955.ogg': 'souscr1-iNat1244955.m4a', 'spbant3/iNat1695874.ogg': 'spbant3-iNat1695874.m4a', 'spispi1/iNat1503058.ogg': 'spispi1-iNat1503058.mp3', 'spispi1/iNat1374076.ogg': 'spispi1-iNat1374076.m4a', 'spispi1/iNat1456192.ogg': 'spispi1-iNat1456192.m4a', 'squcuc1/iNat1358561.ogg': 'squcuc1-iNat1358561.m4a', 'squcuc1/iNat1358573.ogg': 'squcuc1-iNat1358573.m4a', 'squcuc1/iNat188319.ogg': 'squcuc1-iNat188319.m4a', 'strcuc1/iNat1691050.ogg': 'strcuc1-iNat1691050.m4a', 'strcuc1/iNat1675976.ogg': 'strcuc1-iNat1675976.m4a', 'strcuc1/iNat1665191.ogg': 'strcuc1-iNat1665191.m4a', 'strcuc1/iNat1670795.ogg': 'strcuc1-iNat1670795.m4a', 'strcuc1/iNat1165584.ogg': 'strcuc1-iNat1165584.m4a', 'strcuc1/iNat1490053.ogg': 'strcuc1-iNat1490053.m4a', 'strcuc1/iNat1465517.ogg': 'strcuc1-iNat1465517.m4a', 'strcuc1/iNat1367996.ogg': 'strcuc1-iNat1367996.m4a', 'strcuc1/iNat1347727.ogg': 'strcuc1-iNat1347727.m4a', 'strowl1/iNat1451619.ogg': 'strowl1-iNat1451619.m4a', 'strowl1/iNat1736437.ogg': 'strowl1-iNat1736437.m4a', 'strowl1/iNat1537360.ogg': 'strowl1-iNat1537360.m4a', 'swtman1/iNat1468159.ogg': 'swtman1-iNat1468159.m4a', 'swtman1/iNat841931.ogg': 'swtman1-iNat841931.mp3', 'swtman1/iNat980195.ogg': 'swtman1-iNat980195.mp3', 'swtman1/iNat1647280.ogg': 'swtman1-iNat1647280.m4a', 'swtman1/iNat1420444.ogg': 'swtman1-iNat1420444.m4a', 'swtman1/iNat1664402.ogg': 'swtman1-iNat1664402.m4a', 'swtman1/iNat1667664.ogg': 'swtman1-iNat1667664.mp3', 'tattin1/iNat1291008.ogg': 'tattin1-iNat1291008.m4a', 'thlwre1/iNat1446997.ogg': 'thlwre1-iNat1446997.m4a', 'thlwre1/iNat1540292.ogg': 'thlwre1-iNat1540292.m4a', 'toctou1/iNat1406213.ogg': 'toctou1-iNat1406213.m4a', 'trokin/iNat1543761.ogg': 'trokin-iNat1543761.m4a', 'trokin/iNat1088126.ogg': 'trokin-iNat1088126.m4a', 'trokin/iNat1631950.ogg': 'trokin-iNat1631950.m4a', 'trsowl/iNat1337876.ogg': 'trsowl-iNat1337876.m4a', 'trsowl/iNat1321621.ogg': 'trsowl-iNat1321621.m4a', 'trsowl/iNat1240859.ogg': 'trsowl-iNat1240859.mpga', 'trsowl/iNat1707373.ogg': 'trsowl-iNat1707373.m4a', 'trsowl/iNat1608858.ogg': 'trsowl-iNat1608858.m4a', 'varant1/iNat1227614.ogg': 'varant1-iNat1227614.m4a', 'wfwduc1/iNat1679287.ogg': 'wfwduc1-iNat1679287.m4a', 'wfwduc1/iNat1487538.ogg': 'wfwduc1-iNat1487538.m4a', 'whbwar2/iNat763637.ogg': 'whbwar2-iNat763637.m4a', 'whiwoo1/iNat1594296.ogg': 'whiwoo1-iNat1594296.m4a', 'whnjay1/iNat1404548.ogg': 'whnjay1-iNat1404548.m4a', 'whnjay1/iNat1199393.ogg': 'whnjay1-iNat1199393.mpga', 'whnjay1/iNat771603.ogg': 'whnjay1-iNat771603.mp3', 'whnjay1/iNat1636518.ogg': 'whnjay1-iNat1636518.m4a', 'whnjay1/iNat1651360.ogg': 'whnjay1-iNat1651360.m4a', 'whtdov/iNat1536547.ogg': 'whtdov-iNat1536547.m4a', 'whtdov/iNat1594270.ogg': 'whtdov-iNat1594270.m4a', 'whtdov/iNat1598157.ogg': 'whtdov-iNat1598157.m4a', 'y00678/iNat1461732.ogg': 'y00678-iNat1461732.mp3', 'y00678/iNat1593494.ogg': 'y00678-iNat1593494.m4a', 'y00678/iNat1397691.ogg': 'y00678-iNat1397691.m4a', 'yebela1/iNat1593008.ogg': 'yebela1-iNat1593008.m4a', 'yebela1/iNat1479050.ogg': 'yebela1-iNat1479050.mp3', 'yebela1/iNat1521944.ogg': 'yebela1-iNat1521944.m4a', 'yecpar/iNat1360878.ogg': 'yecpar-iNat1360878.m4a', 'yecpar/iNat1347445.ogg': 'yecpar-iNat1347445.mp3', 'yehcar1/iNat1268927.ogg': 'yehcar1-iNat1268927.m4a', 'yehcar1/iNat585409.ogg': 'yehcar1-iNat585409.m4a', 'yehcar1/iNat1701473.ogg': 'yehcar1-iNat1701473.m4a'}
_PATH_MAP = {'/home/salman/Documents/data/birdclef-2026/train_audio/stbwoo2/XC467895.ogg': '/home/salman/Documents/data/download_corrupt/stbwoo2-XC467895.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/1161364/iNat1264238.ogg': '/home/salman/Documents/data/download_corrupt/1161364-iNat1264238.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/209233/iNat1545859.ogg': '/home/salman/Documents/data/download_corrupt/209233-iNat1545859.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/22956/iNat1693371.ogg': '/home/salman/Documents/data/download_corrupt/22956-iNat1693371.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat781822.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat781822.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat1353836.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat1353836.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat1460521.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat1460521.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat1645288.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat1645288.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/23158/iNat1322093.ogg': '/home/salman/Documents/data/download_corrupt/23158-iNat1322093.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/24279/iNat1306335.ogg': '/home/salman/Documents/data/download_corrupt/24279-iNat1306335.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/24279/iNat1435402.ogg': '/home/salman/Documents/data/download_corrupt/24279-iNat1435402.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/244024/iNat1219059.ogg': '/home/salman/Documents/data/download_corrupt/244024-iNat1219059.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/244024/iNat1583846.ogg': '/home/salman/Documents/data/download_corrupt/244024-iNat1583846.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/244024/iNat1573678.ogg': '/home/salman/Documents/data/download_corrupt/244024-iNat1573678.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/25092/iNat1645314.ogg': '/home/salman/Documents/data/download_corrupt/25092-iNat1645314.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/326272/iNat1299066.ogg': '/home/salman/Documents/data/download_corrupt/326272-iNat1299066.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/326272/iNat1303382.ogg': '/home/salman/Documents/data/download_corrupt/326272-iNat1303382.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/43435/iNat1054872.ogg': '/home/salman/Documents/data/download_corrupt/43435-iNat1054872.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/43435/iNat1243480.ogg': '/home/salman/Documents/data/download_corrupt/43435-iNat1243480.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1717935.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1717935.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1346356.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1346356.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1346365.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1346365.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1317366.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1317366.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1559514.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1559514.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1191939.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1191939.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/476521/iNat1648597.ogg': '/home/salman/Documents/data/download_corrupt/476521-iNat1648597.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/555146/iNat1375734.ogg': '/home/salman/Documents/data/download_corrupt/555146-iNat1375734.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/555146/iNat1375753.ogg': '/home/salman/Documents/data/download_corrupt/555146-iNat1375753.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat1372639.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat1372639.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat924044.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat924044.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat924035.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat924035.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat1676955.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat1676955.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/67107/iNat1635719.ogg': '/home/salman/Documents/data/download_corrupt/67107-iNat1635719.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/ashgre1/iNat963674.ogg': '/home/salman/Documents/data/download_corrupt/ashgre1-iNat963674.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/ashgre1/iNat1400791.ogg': '/home/salman/Documents/data/download_corrupt/ashgre1-iNat1400791.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/baffal1/iNat1672327.ogg': '/home/salman/Documents/data/download_corrupt/baffal1-iNat1672327.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/baffal1/iNat1711622.ogg': '/home/salman/Documents/data/download_corrupt/baffal1-iNat1711622.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1638891.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1638891.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1302882.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1302882.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1371833.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1371833.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat335243.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat335243.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1631602.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1631602.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1496209.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1496209.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1630115.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1630115.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat1654575.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat1654575.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat1418545.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat1418545.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat1738725.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat1738725.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat76423.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat76423.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat851301.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat851301.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat851302.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat851302.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat851299.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat851299.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat1275000.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat1275000.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat1517987.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat1517987.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat1710152.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat1710152.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/baymac/iNat1304419.ogg': '/home/salman/Documents/data/download_corrupt/baymac-iNat1304419.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/baymac/iNat976078.ogg': '/home/salman/Documents/data/download_corrupt/baymac-iNat976078.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1318531.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1318531.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat942901.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat942901.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1294916.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1294916.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1338852.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1338852.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1499546.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1499546.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1352566.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1352566.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1543298.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1543298.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1683874.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1683874.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1580446.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1580446.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat418728.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat418728.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat797291.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat797291.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat950353.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat950353.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1333153.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1333153.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat594163.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat594163.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1520789.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1520789.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1705504.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1705504.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bkcdon/iNat1637377.ogg': '/home/salman/Documents/data/download_corrupt/bkcdon-iNat1637377.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bkcdon/iNat1396398.ogg': '/home/salman/Documents/data/download_corrupt/bkcdon-iNat1396398.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bkhpar/iNat1637590.ogg': '/home/salman/Documents/data/download_corrupt/bkhpar-iNat1637590.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bkhpar/iNat1029272.ogg': '/home/salman/Documents/data/download_corrupt/bkhpar-iNat1029272.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/blheag1/iNat1675853.ogg': '/home/salman/Documents/data/download_corrupt/blheag1-iNat1675853.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/blheag1/iNat953708.ogg': '/home/salman/Documents/data/download_corrupt/blheag1-iNat953708.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1422961.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1422961.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1406256.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1406256.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1457501.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1457501.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1554596.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1554596.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1691483.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1691483.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1200017.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1200017.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1556528.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1556528.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1487398.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1487398.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brcmar1/iNat1730049.ogg': '/home/salman/Documents/data/download_corrupt/brcmar1-iNat1730049.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brcmar1/iNat1658256.ogg': '/home/salman/Documents/data/download_corrupt/brcmar1-iNat1658256.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brcmar1/iNat1737157.ogg': '/home/salman/Documents/data/download_corrupt/brcmar1-iNat1737157.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1480534.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1480534.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1706506.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1706506.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1610861.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1610861.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat514729.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat514729.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1491227.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1491227.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1659173.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1659173.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1309637.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1309637.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1548013.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1548013.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1050844.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1050844.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1491232.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1491232.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/bufpar/iNat1295642.ogg': '/home/salman/Documents/data/download_corrupt/bufpar-iNat1295642.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/bufpar/iNat1299514.ogg': '/home/salman/Documents/data/download_corrupt/bufpar-iNat1299514.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/burowl/iNat1589934.ogg': '/home/salman/Documents/data/download_corrupt/burowl-iNat1589934.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/camfli1/iNat1336230.ogg': '/home/salman/Documents/data/download_corrupt/camfli1-iNat1336230.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat228765.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat228765.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat1428711.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat1428711.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat1424302.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat1424302.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat1540294.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat1540294.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat1710475.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat1710475.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat782270.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat782270.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat905814.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat905814.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat826415.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat826415.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat1167591.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat1167591.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat1637929.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat1637929.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat782291.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat782291.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat395438.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat395438.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1591339.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1591339.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat946279.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat946279.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1599244.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1599244.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1672503.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1672503.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1268738.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1268738.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1623767.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1623767.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1321681.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1321681.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1294212.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1294212.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compot1/iNat1668960.ogg': '/home/salman/Documents/data/download_corrupt/compot1-iNat1668960.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/compot1/iNat1660624.ogg': '/home/salman/Documents/data/download_corrupt/compot1-iNat1660624.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1693777.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1693777.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1684518.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1684518.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1678524.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1678524.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1277382.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1277382.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/epaori4/iNat1592245.ogg': '/home/salman/Documents/data/download_corrupt/epaori4-iNat1592245.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/epaori4/iNat649978.ogg': '/home/salman/Documents/data/download_corrupt/epaori4-iNat649978.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/eulfly1/iNat1738901.ogg': '/home/salman/Documents/data/download_corrupt/eulfly1-iNat1738901.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1711295.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1711295.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1664968.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1664968.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1308138.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1308138.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1738605.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1738605.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1240485.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1240485.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1335628.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1335628.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1287848.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1287848.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/fotfly/iNat1193130.ogg': '/home/salman/Documents/data/download_corrupt/fotfly-iNat1193130.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/fusfly1/iNat1518620.ogg': '/home/salman/Documents/data/download_corrupt/fusfly1-iNat1518620.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/giwrai1/iNat1673888.ogg': '/home/salman/Documents/data/download_corrupt/giwrai1-iNat1673888.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/giwrai1/iNat1349850.ogg': '/home/salman/Documents/data/download_corrupt/giwrai1-iNat1349850.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grasal3/iNat1632581.ogg': '/home/salman/Documents/data/download_corrupt/grasal3-iNat1632581.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/grasal3/iNat1644284.ogg': '/home/salman/Documents/data/download_corrupt/grasal3-iNat1644284.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grasal3/iNat1614411.ogg': '/home/salman/Documents/data/download_corrupt/grasal3-iNat1614411.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greant1/iNat1635481.ogg': '/home/salman/Documents/data/download_corrupt/greant1-iNat1635481.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greant1/iNat1508328.ogg': '/home/salman/Documents/data/download_corrupt/greant1-iNat1508328.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greant1/iNat936816.ogg': '/home/salman/Documents/data/download_corrupt/greant1-iNat936816.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/greela/iNat1231355.ogg': '/home/salman/Documents/data/download_corrupt/greela-iNat1231355.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1690035.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1690035.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1572002.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1572002.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1209312.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1209312.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1663561.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1663561.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1400476.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1400476.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1623199.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1623199.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1391832.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1391832.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1667823.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1667823.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1381842.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1381842.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1375792.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1375792.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1375793.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1375793.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1350689.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1350689.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1370909.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1370909.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1638552.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1638552.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat952416.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat952416.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1350614.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1350614.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1303954.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1303954.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grfdov1/iNat1395710.ogg': '/home/salman/Documents/data/download_corrupt/grfdov1-iNat1395710.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/grfdov1/iNat1400824.ogg': '/home/salman/Documents/data/download_corrupt/grfdov1-iNat1400824.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1537449.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1537449.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1288203.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1288203.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1596768.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1596768.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat816375.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat816375.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1255088.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1255088.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1594836.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1594836.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1378299.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1378299.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1346486.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1346486.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1620374.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1620374.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1569899.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1569899.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1624903.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1624903.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1577300.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1577300.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1724472.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1724472.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1683695.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1683695.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1666148.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1666148.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1409352.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1409352.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1364301.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1364301.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1551547.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1551547.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat935753.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat935753.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1397767.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1397767.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1512573.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1512573.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1362595.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1362595.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1417357.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1417357.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1321989.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1321989.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat409684.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat409684.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1304457.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1304457.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1569993.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1569993.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1731791.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1731791.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1316764.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1316764.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1358970.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1358970.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/limpki/iNat1319758.ogg': '/home/salman/Documents/data/download_corrupt/limpki-iNat1319758.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/limpki/iNat1320813.ogg': '/home/salman/Documents/data/download_corrupt/limpki-iNat1320813.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/limpki/iNat1072786.ogg': '/home/salman/Documents/data/download_corrupt/limpki-iNat1072786.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/linwoo1/iNat1302630.ogg': '/home/salman/Documents/data/download_corrupt/linwoo1-iNat1302630.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/linwoo1/iNat1535721.ogg': '/home/salman/Documents/data/download_corrupt/linwoo1-iNat1535721.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/linwoo1/iNat1371736.ogg': '/home/salman/Documents/data/download_corrupt/linwoo1-iNat1371736.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/mabpar/iNat1626097.ogg': '/home/salman/Documents/data/download_corrupt/mabpar-iNat1626097.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/masgna1/iNat1635487.ogg': '/home/salman/Documents/data/download_corrupt/masgna1-iNat1635487.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/oliwoo1/iNat1346713.ogg': '/home/salman/Documents/data/download_corrupt/oliwoo1-iNat1346713.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1687083.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1687083.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1355177.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1355177.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1503877.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1503877.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1657675.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1657675.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1079708.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1079708.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat226664.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat226664.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1398129.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1398129.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1595562.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1595562.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1370949.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1370949.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1692289.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1692289.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1556374.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1556374.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1004549.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1004549.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1670343.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1670343.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat288776.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat288776.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat482127.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat482127.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1135797.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1135797.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1697529.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1697529.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1359848.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1359848.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1361039.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1361039.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1709147.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1709147.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1418628.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1418628.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1418634.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1418634.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1618415.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1618415.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/picpig2/iNat1607749.ogg': '/home/salman/Documents/data/download_corrupt/picpig2-iNat1607749.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/pirfly1/iNat1635054.ogg': '/home/salman/Documents/data/download_corrupt/pirfly1-iNat1635054.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/pirfly1/iNat1677277.ogg': '/home/salman/Documents/data/download_corrupt/pirfly1-iNat1677277.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat911601.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat911601.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat1612345.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat1612345.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat1435256.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat1435256.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat1435257.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat1435257.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rebscy1/iNat1324031.ogg': '/home/salman/Documents/data/download_corrupt/rebscy1-iNat1324031.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/redjun/iNat1661079.ogg': '/home/salman/Documents/data/download_corrupt/redjun-iNat1661079.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/redjun/iNat1681112.ogg': '/home/salman/Documents/data/download_corrupt/redjun-iNat1681112.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/redjun/iNat953958.ogg': '/home/salman/Documents/data/download_corrupt/redjun-iNat953958.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/relser1/iNat1557442.ogg': '/home/salman/Documents/data/download_corrupt/relser1-iNat1557442.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/relser1/iNat1370757.ogg': '/home/salman/Documents/data/download_corrupt/relser1-iNat1370757.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/relser1/iNat1344314.ogg': '/home/salman/Documents/data/download_corrupt/relser1-iNat1344314.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/roahaw/iNat1677378.ogg': '/home/salman/Documents/data/download_corrupt/roahaw-iNat1677378.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/roahaw/iNat1458636.ogg': '/home/salman/Documents/data/download_corrupt/roahaw-iNat1458636.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat870811.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat870811.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1684073.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1684073.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat852442.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat852442.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1682587.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1682587.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1672514.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1672514.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat546228.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat546228.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat850316.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat850316.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1707784.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1707784.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1615216.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1615216.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat851551.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat851551.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1691551.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1691551.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1691430.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1691430.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rufnig1/iNat1657250.ogg': '/home/salman/Documents/data/download_corrupt/rufnig1-iNat1657250.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/rumfly1/iNat1734627.ogg': '/home/salman/Documents/data/download_corrupt/rumfly1-iNat1734627.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/ruther1/iNat1483642.ogg': '/home/salman/Documents/data/download_corrupt/ruther1-iNat1483642.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1692175.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1692175.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1313823.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1313823.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1300076.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1300076.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1300148.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1300148.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1667770.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1667770.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1449859.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1449859.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/saytan1/iNat1677185.ogg': '/home/salman/Documents/data/download_corrupt/saytan1-iNat1677185.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/scadov1/iNat1299298.ogg': '/home/salman/Documents/data/download_corrupt/scadov1-iNat1299298.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/scadov1/iNat1491465.ogg': '/home/salman/Documents/data/download_corrupt/scadov1-iNat1491465.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/scadov1/iNat1276971.ogg': '/home/salman/Documents/data/download_corrupt/scadov1-iNat1276971.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/schpar1/iNat1293642.ogg': '/home/salman/Documents/data/download_corrupt/schpar1-iNat1293642.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1321023.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1321023.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1532661.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1532661.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1345739.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1345739.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1471076.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1471076.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shshaw/iNat1590156.ogg': '/home/salman/Documents/data/download_corrupt/shshaw-iNat1590156.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shshaw/iNat1602640.ogg': '/home/salman/Documents/data/download_corrupt/shshaw-iNat1602640.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat869228.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat869228.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat870997.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat870997.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat870998.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat870998.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat1696713.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat1696713.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/sibtan2/iNat1402979.ogg': '/home/salman/Documents/data/download_corrupt/sibtan2-iNat1402979.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/smbani/iNat915724.ogg': '/home/salman/Documents/data/download_corrupt/smbani-iNat915724.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/smbani/iNat1594767.ogg': '/home/salman/Documents/data/download_corrupt/smbani-iNat1594767.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/smbtin1/iNat1734628.ogg': '/home/salman/Documents/data/download_corrupt/smbtin1-iNat1734628.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/smbtin1/iNat81751.ogg': '/home/salman/Documents/data/download_corrupt/smbtin1-iNat81751.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/sobcac1/iNat1387094.ogg': '/home/salman/Documents/data/download_corrupt/sobcac1-iNat1387094.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/sobcac1/iNat1432132.ogg': '/home/salman/Documents/data/download_corrupt/sobcac1-iNat1432132.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/sobtyr1/iNat1718955.ogg': '/home/salman/Documents/data/download_corrupt/sobtyr1-iNat1718955.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/sobtyr1/iNat1355327.ogg': '/home/salman/Documents/data/download_corrupt/sobtyr1-iNat1355327.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1701203.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1701203.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1685298.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1685298.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1705430.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1705430.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1687317.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1687317.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1181651.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1181651.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat671916.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat671916.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat797558.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat797558.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/sofspi1/iNat1664377.ogg': '/home/salman/Documents/data/download_corrupt/sofspi1-iNat1664377.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/sofspi1/iNat1510202.ogg': '/home/salman/Documents/data/download_corrupt/sofspi1-iNat1510202.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1203529.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1203529.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1405995.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1405995.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1637171.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1637171.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1637169.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1637169.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1685486.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1685486.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1434604.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1434604.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/souscr1/iNat1244955.ogg': '/home/salman/Documents/data/download_corrupt/souscr1-iNat1244955.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/spbant3/iNat1695874.ogg': '/home/salman/Documents/data/download_corrupt/spbant3-iNat1695874.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/spispi1/iNat1503058.ogg': '/home/salman/Documents/data/download_corrupt/spispi1-iNat1503058.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/spispi1/iNat1374076.ogg': '/home/salman/Documents/data/download_corrupt/spispi1-iNat1374076.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/spispi1/iNat1456192.ogg': '/home/salman/Documents/data/download_corrupt/spispi1-iNat1456192.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/squcuc1/iNat1358561.ogg': '/home/salman/Documents/data/download_corrupt/squcuc1-iNat1358561.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/squcuc1/iNat1358573.ogg': '/home/salman/Documents/data/download_corrupt/squcuc1-iNat1358573.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/squcuc1/iNat188319.ogg': '/home/salman/Documents/data/download_corrupt/squcuc1-iNat188319.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1691050.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1691050.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1675976.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1675976.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1665191.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1665191.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1670795.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1670795.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1165584.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1165584.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1490053.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1490053.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1465517.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1465517.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1367996.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1367996.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1347727.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1347727.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strowl1/iNat1451619.ogg': '/home/salman/Documents/data/download_corrupt/strowl1-iNat1451619.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strowl1/iNat1736437.ogg': '/home/salman/Documents/data/download_corrupt/strowl1-iNat1736437.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/strowl1/iNat1537360.ogg': '/home/salman/Documents/data/download_corrupt/strowl1-iNat1537360.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1468159.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1468159.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat841931.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat841931.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat980195.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat980195.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1647280.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1647280.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1420444.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1420444.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1664402.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1664402.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1667664.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1667664.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/tattin1/iNat1291008.ogg': '/home/salman/Documents/data/download_corrupt/tattin1-iNat1291008.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/thlwre1/iNat1446997.ogg': '/home/salman/Documents/data/download_corrupt/thlwre1-iNat1446997.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/thlwre1/iNat1540292.ogg': '/home/salman/Documents/data/download_corrupt/thlwre1-iNat1540292.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/toctou1/iNat1406213.ogg': '/home/salman/Documents/data/download_corrupt/toctou1-iNat1406213.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trokin/iNat1543761.ogg': '/home/salman/Documents/data/download_corrupt/trokin-iNat1543761.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trokin/iNat1088126.ogg': '/home/salman/Documents/data/download_corrupt/trokin-iNat1088126.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trokin/iNat1631950.ogg': '/home/salman/Documents/data/download_corrupt/trokin-iNat1631950.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1337876.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1337876.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1321621.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1321621.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1240859.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1240859.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1707373.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1707373.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1608858.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1608858.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/varant1/iNat1227614.ogg': '/home/salman/Documents/data/download_corrupt/varant1-iNat1227614.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/wfwduc1/iNat1679287.ogg': '/home/salman/Documents/data/download_corrupt/wfwduc1-iNat1679287.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/wfwduc1/iNat1487538.ogg': '/home/salman/Documents/data/download_corrupt/wfwduc1-iNat1487538.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whbwar2/iNat763637.ogg': '/home/salman/Documents/data/download_corrupt/whbwar2-iNat763637.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whiwoo1/iNat1594296.ogg': '/home/salman/Documents/data/download_corrupt/whiwoo1-iNat1594296.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1404548.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1404548.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1199393.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1199393.mpga', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat771603.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat771603.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1636518.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1636518.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1651360.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1651360.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whtdov/iNat1536547.ogg': '/home/salman/Documents/data/download_corrupt/whtdov-iNat1536547.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whtdov/iNat1594270.ogg': '/home/salman/Documents/data/download_corrupt/whtdov-iNat1594270.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/whtdov/iNat1598157.ogg': '/home/salman/Documents/data/download_corrupt/whtdov-iNat1598157.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/y00678/iNat1461732.ogg': '/home/salman/Documents/data/download_corrupt/y00678-iNat1461732.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/y00678/iNat1593494.ogg': '/home/salman/Documents/data/download_corrupt/y00678-iNat1593494.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/y00678/iNat1397691.ogg': '/home/salman/Documents/data/download_corrupt/y00678-iNat1397691.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/yebela1/iNat1593008.ogg': '/home/salman/Documents/data/download_corrupt/yebela1-iNat1593008.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/yebela1/iNat1479050.ogg': '/home/salman/Documents/data/download_corrupt/yebela1-iNat1479050.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/yebela1/iNat1521944.ogg': '/home/salman/Documents/data/download_corrupt/yebela1-iNat1521944.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/yecpar/iNat1360878.ogg': '/home/salman/Documents/data/download_corrupt/yecpar-iNat1360878.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/yecpar/iNat1347445.ogg': '/home/salman/Documents/data/download_corrupt/yecpar-iNat1347445.mp3', '/home/salman/Documents/data/birdclef-2026/train_audio/yehcar1/iNat1268927.ogg': '/home/salman/Documents/data/download_corrupt/yehcar1-iNat1268927.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/yehcar1/iNat585409.ogg': '/home/salman/Documents/data/download_corrupt/yehcar1-iNat585409.m4a', '/home/salman/Documents/data/birdclef-2026/train_audio/yehcar1/iNat1701473.ogg': '/home/salman/Documents/data/download_corrupt/yehcar1-iNat1701473.m4a'}

FILE_MAP = {'stbwoo2/XC467895.ogg': 'stbwoo2-XC467895.ogg', '1161364/iNat1264238.ogg': '1161364-iNat1264238.ogg', '209233/iNat1545859.ogg': '209233-iNat1545859.ogg', '22956/iNat1693371.ogg': '22956-iNat1693371.ogg', '22973/iNat781822.ogg': '22973-iNat781822.ogg', '22973/iNat1353836.ogg': '22973-iNat1353836.ogg', '22973/iNat1460521.ogg': '22973-iNat1460521.ogg', '22973/iNat1645288.ogg': '22973-iNat1645288.ogg', '23158/iNat1322093.ogg': '23158-iNat1322093.ogg', '24279/iNat1306335.ogg': '24279-iNat1306335.ogg', '24279/iNat1435402.ogg': '24279-iNat1435402.ogg', '244024/iNat1219059.ogg': '244024-iNat1219059.ogg', '244024/iNat1583846.ogg': '244024-iNat1583846.ogg', '244024/iNat1573678.ogg': '244024-iNat1573678.ogg', '25092/iNat1645314.ogg': '25092-iNat1645314.ogg', '326272/iNat1299066.ogg': '326272-iNat1299066.ogg', '326272/iNat1303382.ogg': '326272-iNat1303382.ogg', '43435/iNat1054872.ogg': '43435-iNat1054872.ogg', '43435/iNat1243480.ogg': '43435-iNat1243480.ogg', '47144/iNat1717935.ogg': '47144-iNat1717935.ogg', '47144/iNat1346356.ogg': '47144-iNat1346356.ogg', '47144/iNat1346365.ogg': '47144-iNat1346365.ogg', '47144/iNat1317366.ogg': '47144-iNat1317366.ogg', '47144/iNat1559514.ogg': '47144-iNat1559514.ogg', '47144/iNat1191939.ogg': '47144-iNat1191939.ogg', '476521/iNat1648597.ogg': '476521-iNat1648597.ogg', '555146/iNat1375734.ogg': '555146-iNat1375734.ogg', '555146/iNat1375753.ogg': '555146-iNat1375753.ogg', '65377/iNat1372639.ogg': '65377-iNat1372639.ogg', '65377/iNat924044.ogg': '65377-iNat924044.ogg', '65377/iNat924035.ogg': '65377-iNat924035.ogg', '65377/iNat1676955.ogg': '65377-iNat1676955.ogg', '67107/iNat1635719.ogg': '67107-iNat1635719.ogg', 'ashgre1/iNat963674.ogg': 'ashgre1-iNat963674.ogg', 'ashgre1/iNat1400791.ogg': 'ashgre1-iNat1400791.ogg', 'baffal1/iNat1672327.ogg': 'baffal1-iNat1672327.ogg', 'baffal1/iNat1711622.ogg': 'baffal1-iNat1711622.ogg', 'banana/iNat1638891.ogg': 'banana-iNat1638891.ogg', 'banana/iNat1302882.ogg': 'banana-iNat1302882.ogg', 'banana/iNat1371833.ogg': 'banana-iNat1371833.ogg', 'banana/iNat335243.ogg': 'banana-iNat335243.ogg', 'banana/iNat1631602.ogg': 'banana-iNat1631602.ogg', 'banana/iNat1496209.ogg': 'banana-iNat1496209.ogg', 'banana/iNat1630115.ogg': 'banana-iNat1630115.ogg', 'barant1/iNat1654575.ogg': 'barant1-iNat1654575.ogg', 'barant1/iNat1418545.ogg': 'barant1-iNat1418545.ogg', 'barant1/iNat1738725.ogg': 'barant1-iNat1738725.ogg', 'barant1/iNat76423.ogg': 'barant1-iNat76423.ogg', 'batbel1/iNat851301.ogg': 'batbel1-iNat851301.ogg', 'batbel1/iNat851302.ogg': 'batbel1-iNat851302.ogg', 'batbel1/iNat851299.ogg': 'batbel1-iNat851299.ogg', 'batbel1/iNat1275000.ogg': 'batbel1-iNat1275000.ogg', 'batbel1/iNat1517987.ogg': 'batbel1-iNat1517987.ogg', 'batbel1/iNat1710152.ogg': 'batbel1-iNat1710152.ogg', 'baymac/iNat1304419.ogg': 'baymac-iNat1304419.ogg', 'baymac/iNat976078.ogg': 'baymac-iNat976078.ogg', 'bbwduc/iNat1318531.ogg': 'bbwduc-iNat1318531.ogg', 'bbwduc/iNat942901.ogg': 'bbwduc-iNat942901.ogg', 'bbwduc/iNat1294916.ogg': 'bbwduc-iNat1294916.ogg', 'bbwduc/iNat1338852.ogg': 'bbwduc-iNat1338852.ogg', 'bbwduc/iNat1499546.ogg': 'bbwduc-iNat1499546.ogg', 'bbwduc/iNat1352566.ogg': 'bbwduc-iNat1352566.ogg', 'bbwduc/iNat1543298.ogg': 'bbwduc-iNat1543298.ogg', 'bbwduc/iNat1683874.ogg': 'bbwduc-iNat1683874.ogg', 'bbwduc/iNat1580446.ogg': 'bbwduc-iNat1580446.ogg', 'bbwduc/iNat418728.ogg': 'bbwduc-iNat418728.ogg', 'bbwduc/iNat797291.ogg': 'bbwduc-iNat797291.ogg', 'bbwduc/iNat950353.ogg': 'bbwduc-iNat950353.ogg', 'bbwduc/iNat1333153.ogg': 'bbwduc-iNat1333153.ogg', 'bbwduc/iNat594163.ogg': 'bbwduc-iNat594163.ogg', 'bbwduc/iNat1520789.ogg': 'bbwduc-iNat1520789.ogg', 'bbwduc/iNat1705504.ogg': 'bbwduc-iNat1705504.ogg', 'bkcdon/iNat1637377.ogg': 'bkcdon-iNat1637377.ogg', 'bkcdon/iNat1396398.ogg': 'bkcdon-iNat1396398.ogg', 'bkhpar/iNat1637590.ogg': 'bkhpar-iNat1637590.ogg', 'bkhpar/iNat1029272.ogg': 'bkhpar-iNat1029272.ogg', 'blheag1/iNat1675853.ogg': 'blheag1-iNat1675853.ogg', 'blheag1/iNat953708.ogg': 'blheag1-iNat953708.ogg', 'bncfly/iNat1422961.ogg': 'bncfly-iNat1422961.ogg', 'bncfly/iNat1406256.ogg': 'bncfly-iNat1406256.ogg', 'bncfly/iNat1457501.ogg': 'bncfly-iNat1457501.ogg', 'bncfly/iNat1554596.ogg': 'bncfly-iNat1554596.ogg', 'bobfly1/iNat1691483.ogg': 'bobfly1-iNat1691483.ogg', 'bobfly1/iNat1200017.ogg': 'bobfly1-iNat1200017.ogg', 'bobfly1/iNat1556528.ogg': 'bobfly1-iNat1556528.ogg', 'bobfly1/iNat1487398.ogg': 'bobfly1-iNat1487398.ogg', 'brcmar1/iNat1730049.ogg': 'brcmar1-iNat1730049.ogg', 'brcmar1/iNat1658256.ogg': 'brcmar1-iNat1658256.ogg', 'brcmar1/iNat1737157.ogg': 'brcmar1-iNat1737157.ogg', 'brnowl/iNat1480534.ogg': 'brnowl-iNat1480534.ogg', 'brnowl/iNat1706506.ogg': 'brnowl-iNat1706506.ogg', 'brnowl/iNat1610861.ogg': 'brnowl-iNat1610861.ogg', 'brnowl/iNat514729.ogg': 'brnowl-iNat514729.ogg', 'brnowl/iNat1491227.ogg': 'brnowl-iNat1491227.ogg', 'brnowl/iNat1659173.ogg': 'brnowl-iNat1659173.ogg', 'brnowl/iNat1309637.ogg': 'brnowl-iNat1309637.ogg', 'brnowl/iNat1548013.ogg': 'brnowl-iNat1548013.ogg', 'brnowl/iNat1050844.ogg': 'brnowl-iNat1050844.ogg', 'brnowl/iNat1491232.ogg': 'brnowl-iNat1491232.ogg', 'bufpar/iNat1295642.ogg': 'bufpar-iNat1295642.ogg', 'bufpar/iNat1299514.ogg': 'bufpar-iNat1299514.ogg', 'burowl/iNat1589934.ogg': 'burowl-iNat1589934.ogg', 'camfli1/iNat1336230.ogg': 'camfli1-iNat1336230.ogg', 'chobla1/iNat228765.ogg': 'chobla1-iNat228765.ogg', 'chobla1/iNat1428711.ogg': 'chobla1-iNat1428711.ogg', 'chobla1/iNat1424302.ogg': 'chobla1-iNat1424302.ogg', 'chobla1/iNat1540294.ogg': 'chobla1-iNat1540294.ogg', 'coffal1/iNat1710475.ogg': 'coffal1-iNat1710475.ogg', 'coffal1/iNat782270.ogg': 'coffal1-iNat782270.ogg', 'coffal1/iNat905814.ogg': 'coffal1-iNat905814.ogg', 'coffal1/iNat826415.ogg': 'coffal1-iNat826415.ogg', 'coffal1/iNat1167591.ogg': 'coffal1-iNat1167591.ogg', 'coffal1/iNat1637929.ogg': 'coffal1-iNat1637929.ogg', 'coffal1/iNat782291.ogg': 'coffal1-iNat782291.ogg', 'coffal1/iNat395438.ogg': 'coffal1-iNat395438.ogg', 'compau/iNat1591339.ogg': 'compau-iNat1591339.ogg', 'compau/iNat946279.ogg': 'compau-iNat946279.ogg', 'compau/iNat1599244.ogg': 'compau-iNat1599244.ogg', 'compau/iNat1672503.ogg': 'compau-iNat1672503.ogg', 'compau/iNat1268738.ogg': 'compau-iNat1268738.ogg', 'compau/iNat1623767.ogg': 'compau-iNat1623767.ogg', 'compau/iNat1321681.ogg': 'compau-iNat1321681.ogg', 'compau/iNat1294212.ogg': 'compau-iNat1294212.ogg', 'compot1/iNat1668960.ogg': 'compot1-iNat1668960.ogg', 'compot1/iNat1660624.ogg': 'compot1-iNat1660624.ogg', 'crbthr1/iNat1693777.ogg': 'crbthr1-iNat1693777.ogg', 'crbthr1/iNat1684518.ogg': 'crbthr1-iNat1684518.ogg', 'crbthr1/iNat1678524.ogg': 'crbthr1-iNat1678524.ogg', 'crbthr1/iNat1277382.ogg': 'crbthr1-iNat1277382.ogg', 'epaori4/iNat1592245.ogg': 'epaori4-iNat1592245.ogg', 'epaori4/iNat649978.ogg': 'epaori4-iNat649978.ogg', 'eulfly1/iNat1738901.ogg': 'eulfly1-iNat1738901.ogg', 'fepowl/iNat1711295.ogg': 'fepowl-iNat1711295.ogg', 'fepowl/iNat1664968.ogg': 'fepowl-iNat1664968.ogg', 'fepowl/iNat1308138.ogg': 'fepowl-iNat1308138.ogg', 'fepowl/iNat1738605.ogg': 'fepowl-iNat1738605.ogg', 'fepowl/iNat1240485.ogg': 'fepowl-iNat1240485.ogg', 'fepowl/iNat1335628.ogg': 'fepowl-iNat1335628.ogg', 'fepowl/iNat1287848.ogg': 'fepowl-iNat1287848.ogg', 'fotfly/iNat1193130.ogg': 'fotfly-iNat1193130.ogg', 'fusfly1/iNat1518620.ogg': 'fusfly1-iNat1518620.ogg', 'giwrai1/iNat1673888.ogg': 'giwrai1-iNat1673888.ogg', 'giwrai1/iNat1349850.ogg': 'giwrai1-iNat1349850.ogg', 'grasal3/iNat1632581.ogg': 'grasal3-iNat1632581.ogg', 'grasal3/iNat1644284.ogg': 'grasal3-iNat1644284.ogg', 'grasal3/iNat1614411.ogg': 'grasal3-iNat1614411.ogg', 'greant1/iNat1635481.ogg': 'greant1-iNat1635481.ogg', 'greant1/iNat1508328.ogg': 'greant1-iNat1508328.ogg', 'greant1/iNat936816.ogg': 'greant1-iNat936816.ogg', 'greela/iNat1231355.ogg': 'greela-iNat1231355.ogg', 'grekis/iNat1690035.ogg': 'grekis-iNat1690035.ogg', 'grekis/iNat1572002.ogg': 'grekis-iNat1572002.ogg', 'grekis/iNat1209312.ogg': 'grekis-iNat1209312.ogg', 'grekis/iNat1663561.ogg': 'grekis-iNat1663561.ogg', 'grekis/iNat1400476.ogg': 'grekis-iNat1400476.ogg', 'grekis/iNat1623199.ogg': 'grekis-iNat1623199.ogg', 'grekis/iNat1391832.ogg': 'grekis-iNat1391832.ogg', 'grekis/iNat1667823.ogg': 'grekis-iNat1667823.ogg', 'greyel/iNat1381842.ogg': 'greyel-iNat1381842.ogg', 'greyel/iNat1375792.ogg': 'greyel-iNat1375792.ogg', 'greyel/iNat1375793.ogg': 'greyel-iNat1375793.ogg', 'greyel/iNat1350689.ogg': 'greyel-iNat1350689.ogg', 'greyel/iNat1370909.ogg': 'greyel-iNat1370909.ogg', 'greyel/iNat1638552.ogg': 'greyel-iNat1638552.ogg', 'greyel/iNat952416.ogg': 'greyel-iNat952416.ogg', 'greyel/iNat1350614.ogg': 'greyel-iNat1350614.ogg', 'greyel/iNat1303954.ogg': 'greyel-iNat1303954.ogg', 'grfdov1/iNat1395710.ogg': 'grfdov1-iNat1395710.ogg', 'grfdov1/iNat1400824.ogg': 'grfdov1-iNat1400824.ogg', 'gycwor1/iNat1537449.ogg': 'gycwor1-iNat1537449.ogg', 'gycwor1/iNat1288203.ogg': 'gycwor1-iNat1288203.ogg', 'gycwor1/iNat1596768.ogg': 'gycwor1-iNat1596768.ogg', 'gycwor1/iNat816375.ogg': 'gycwor1-iNat816375.ogg', 'gycwor1/iNat1255088.ogg': 'gycwor1-iNat1255088.ogg', 'gycwor1/iNat1594836.ogg': 'gycwor1-iNat1594836.ogg', 'gycwor1/iNat1378299.ogg': 'gycwor1-iNat1378299.ogg', 'gycwor1/iNat1346486.ogg': 'gycwor1-iNat1346486.ogg', 'gycwor1/iNat1620374.ogg': 'gycwor1-iNat1620374.ogg', 'gycwor1/iNat1569899.ogg': 'gycwor1-iNat1569899.ogg', 'gycwor1/iNat1624903.ogg': 'gycwor1-iNat1624903.ogg', 'gycwor1/iNat1577300.ogg': 'gycwor1-iNat1577300.ogg', 'gycwor1/iNat1724472.ogg': 'gycwor1-iNat1724472.ogg', 'gycwor1/iNat1683695.ogg': 'gycwor1-iNat1683695.ogg', 'houspa/iNat1666148.ogg': 'houspa-iNat1666148.ogg', 'houspa/iNat1409352.ogg': 'houspa-iNat1409352.ogg', 'houspa/iNat1364301.ogg': 'houspa-iNat1364301.ogg', 'houspa/iNat1551547.ogg': 'houspa-iNat1551547.ogg', 'houspa/iNat935753.ogg': 'houspa-iNat935753.ogg', 'houspa/iNat1397767.ogg': 'houspa-iNat1397767.ogg', 'houspa/iNat1512573.ogg': 'houspa-iNat1512573.ogg', 'houspa/iNat1362595.ogg': 'houspa-iNat1362595.ogg', 'houspa/iNat1417357.ogg': 'houspa-iNat1417357.ogg', 'houspa/iNat1321989.ogg': 'houspa-iNat1321989.ogg', 'houspa/iNat409684.ogg': 'houspa-iNat409684.ogg', 'houspa/iNat1304457.ogg': 'houspa-iNat1304457.ogg', 'houspa/iNat1569993.ogg': 'houspa-iNat1569993.ogg', 'houspa/iNat1731791.ogg': 'houspa-iNat1731791.ogg', 'houspa/iNat1316764.ogg': 'houspa-iNat1316764.ogg', 'houspa/iNat1358970.ogg': 'houspa-iNat1358970.ogg', 'limpki/iNat1319758.ogg': 'limpki-iNat1319758.ogg', 'limpki/iNat1320813.ogg': 'limpki-iNat1320813.ogg', 'limpki/iNat1072786.ogg': 'limpki-iNat1072786.ogg', 'linwoo1/iNat1302630.ogg': 'linwoo1-iNat1302630.ogg', 'linwoo1/iNat1535721.ogg': 'linwoo1-iNat1535721.ogg', 'linwoo1/iNat1371736.ogg': 'linwoo1-iNat1371736.ogg', 'mabpar/iNat1626097.ogg': 'mabpar-iNat1626097.ogg', 'masgna1/iNat1635487.ogg': 'masgna1-iNat1635487.ogg', 'oliwoo1/iNat1346713.ogg': 'oliwoo1-iNat1346713.ogg', 'orwpar/iNat1687083.ogg': 'orwpar-iNat1687083.ogg', 'orwpar/iNat1355177.ogg': 'orwpar-iNat1355177.ogg', 'orwpar/iNat1503877.ogg': 'orwpar-iNat1503877.ogg', 'orwpar/iNat1657675.ogg': 'orwpar-iNat1657675.ogg', 'orwpar/iNat1079708.ogg': 'orwpar-iNat1079708.ogg', 'osprey/iNat226664.ogg': 'osprey-iNat226664.ogg', 'osprey/iNat1398129.ogg': 'osprey-iNat1398129.ogg', 'osprey/iNat1595562.ogg': 'osprey-iNat1595562.ogg', 'osprey/iNat1370949.ogg': 'osprey-iNat1370949.ogg', 'osprey/iNat1692289.ogg': 'osprey-iNat1692289.ogg', 'osprey/iNat1556374.ogg': 'osprey-iNat1556374.ogg', 'osprey/iNat1004549.ogg': 'osprey-iNat1004549.ogg', 'osprey/iNat1670343.ogg': 'osprey-iNat1670343.ogg', 'osprey/iNat288776.ogg': 'osprey-iNat288776.ogg', 'osprey/iNat482127.ogg': 'osprey-iNat482127.ogg', 'osprey/iNat1135797.ogg': 'osprey-iNat1135797.ogg', 'osprey/iNat1697529.ogg': 'osprey-iNat1697529.ogg', 'osprey/iNat1359848.ogg': 'osprey-iNat1359848.ogg', 'osprey/iNat1361039.ogg': 'osprey-iNat1361039.ogg', 'paltan1/iNat1709147.ogg': 'paltan1-iNat1709147.ogg', 'paltan1/iNat1418628.ogg': 'paltan1-iNat1418628.ogg', 'paltan1/iNat1418634.ogg': 'paltan1-iNat1418634.ogg', 'paltan1/iNat1618415.ogg': 'paltan1-iNat1618415.ogg', 'picpig2/iNat1607749.ogg': 'picpig2-iNat1607749.ogg', 'pirfly1/iNat1635054.ogg': 'pirfly1-iNat1635054.ogg', 'pirfly1/iNat1677277.ogg': 'pirfly1-iNat1677277.ogg', 'plcjay1/iNat911601.ogg': 'plcjay1-iNat911601.ogg', 'plcjay1/iNat1612345.ogg': 'plcjay1-iNat1612345.ogg', 'plcjay1/iNat1435256.ogg': 'plcjay1-iNat1435256.ogg', 'plcjay1/iNat1435257.ogg': 'plcjay1-iNat1435257.ogg', 'rebscy1/iNat1324031.ogg': 'rebscy1-iNat1324031.ogg', 'redjun/iNat1661079.ogg': 'redjun-iNat1661079.ogg', 'redjun/iNat1681112.ogg': 'redjun-iNat1681112.ogg', 'redjun/iNat953958.ogg': 'redjun-iNat953958.ogg', 'relser1/iNat1557442.ogg': 'relser1-iNat1557442.ogg', 'relser1/iNat1370757.ogg': 'relser1-iNat1370757.ogg', 'relser1/iNat1344314.ogg': 'relser1-iNat1344314.ogg', 'roahaw/iNat1677378.ogg': 'roahaw-iNat1677378.ogg', 'roahaw/iNat1458636.ogg': 'roahaw-iNat1458636.ogg', 'rubthr1/iNat870811.ogg': 'rubthr1-iNat870811.ogg', 'rubthr1/iNat1684073.ogg': 'rubthr1-iNat1684073.ogg', 'rubthr1/iNat852442.ogg': 'rubthr1-iNat852442.ogg', 'rubthr1/iNat1682587.ogg': 'rubthr1-iNat1682587.ogg', 'rubthr1/iNat1672514.ogg': 'rubthr1-iNat1672514.ogg', 'rubthr1/iNat546228.ogg': 'rubthr1-iNat546228.ogg', 'rubthr1/iNat850316.ogg': 'rubthr1-iNat850316.ogg', 'rubthr1/iNat1707784.ogg': 'rubthr1-iNat1707784.ogg', 'rubthr1/iNat1615216.ogg': 'rubthr1-iNat1615216.ogg', 'rubthr1/iNat851551.ogg': 'rubthr1-iNat851551.ogg', 'rubthr1/iNat1691551.ogg': 'rubthr1-iNat1691551.ogg', 'rubthr1/iNat1691430.ogg': 'rubthr1-iNat1691430.ogg', 'rufnig1/iNat1657250.ogg': 'rufnig1-iNat1657250.ogg', 'rumfly1/iNat1734627.ogg': 'rumfly1-iNat1734627.ogg', 'ruther1/iNat1483642.ogg': 'ruther1-iNat1483642.ogg', 'saffin/iNat1692175.ogg': 'saffin-iNat1692175.ogg', 'saffin/iNat1313823.ogg': 'saffin-iNat1313823.ogg', 'saffin/iNat1300076.ogg': 'saffin-iNat1300076.ogg', 'saffin/iNat1300148.ogg': 'saffin-iNat1300148.ogg', 'saffin/iNat1667770.ogg': 'saffin-iNat1667770.ogg', 'saffin/iNat1449859.ogg': 'saffin-iNat1449859.ogg', 'saytan1/iNat1677185.ogg': 'saytan1-iNat1677185.ogg', 'scadov1/iNat1299298.ogg': 'scadov1-iNat1299298.ogg', 'scadov1/iNat1491465.ogg': 'scadov1-iNat1491465.ogg', 'scadov1/iNat1276971.ogg': 'scadov1-iNat1276971.ogg', 'schpar1/iNat1293642.ogg': 'schpar1-iNat1293642.ogg', 'shcfly1/iNat1321023.ogg': 'shcfly1-iNat1321023.ogg', 'shcfly1/iNat1532661.ogg': 'shcfly1-iNat1532661.ogg', 'shcfly1/iNat1345739.ogg': 'shcfly1-iNat1345739.ogg', 'shcfly1/iNat1471076.ogg': 'shcfly1-iNat1471076.ogg', 'shshaw/iNat1590156.ogg': 'shshaw-iNat1590156.ogg', 'shshaw/iNat1602640.ogg': 'shshaw-iNat1602640.ogg', 'shtnig1/iNat869228.ogg': 'shtnig1-iNat869228.ogg', 'shtnig1/iNat870997.ogg': 'shtnig1-iNat870997.ogg', 'shtnig1/iNat870998.ogg': 'shtnig1-iNat870998.ogg', 'shtnig1/iNat1696713.ogg': 'shtnig1-iNat1696713.ogg', 'sibtan2/iNat1402979.ogg': 'sibtan2-iNat1402979.ogg', 'smbani/iNat915724.ogg': 'smbani-iNat915724.ogg', 'smbani/iNat1594767.ogg': 'smbani-iNat1594767.ogg', 'smbtin1/iNat1734628.ogg': 'smbtin1-iNat1734628.ogg', 'smbtin1/iNat81751.ogg': 'smbtin1-iNat81751.ogg', 'sobcac1/iNat1387094.ogg': 'sobcac1-iNat1387094.ogg', 'sobcac1/iNat1432132.ogg': 'sobcac1-iNat1432132.ogg', 'sobtyr1/iNat1718955.ogg': 'sobtyr1-iNat1718955.ogg', 'sobtyr1/iNat1355327.ogg': 'sobtyr1-iNat1355327.ogg', 'socfly1/iNat1701203.ogg': 'socfly1-iNat1701203.ogg', 'socfly1/iNat1685298.ogg': 'socfly1-iNat1685298.ogg', 'socfly1/iNat1705430.ogg': 'socfly1-iNat1705430.ogg', 'socfly1/iNat1687317.ogg': 'socfly1-iNat1687317.ogg', 'socfly1/iNat1181651.ogg': 'socfly1-iNat1181651.ogg', 'socfly1/iNat671916.ogg': 'socfly1-iNat671916.ogg', 'socfly1/iNat797558.ogg': 'socfly1-iNat797558.ogg', 'sofspi1/iNat1664377.ogg': 'sofspi1-iNat1664377.ogg', 'sofspi1/iNat1510202.ogg': 'sofspi1-iNat1510202.ogg', 'soulap1/iNat1203529.ogg': 'soulap1-iNat1203529.ogg', 'soulap1/iNat1405995.ogg': 'soulap1-iNat1405995.ogg', 'soulap1/iNat1637171.ogg': 'soulap1-iNat1637171.ogg', 'soulap1/iNat1637169.ogg': 'soulap1-iNat1637169.ogg', 'soulap1/iNat1685486.ogg': 'soulap1-iNat1685486.ogg', 'soulap1/iNat1434604.ogg': 'soulap1-iNat1434604.ogg', 'souscr1/iNat1244955.ogg': 'souscr1-iNat1244955.ogg', 'spbant3/iNat1695874.ogg': 'spbant3-iNat1695874.ogg', 'spispi1/iNat1503058.ogg': 'spispi1-iNat1503058.ogg', 'spispi1/iNat1374076.ogg': 'spispi1-iNat1374076.ogg', 'spispi1/iNat1456192.ogg': 'spispi1-iNat1456192.ogg', 'squcuc1/iNat1358561.ogg': 'squcuc1-iNat1358561.ogg', 'squcuc1/iNat1358573.ogg': 'squcuc1-iNat1358573.ogg', 'squcuc1/iNat188319.ogg': 'squcuc1-iNat188319.ogg', 'strcuc1/iNat1691050.ogg': 'strcuc1-iNat1691050.ogg', 'strcuc1/iNat1675976.ogg': 'strcuc1-iNat1675976.ogg', 'strcuc1/iNat1665191.ogg': 'strcuc1-iNat1665191.ogg', 'strcuc1/iNat1670795.ogg': 'strcuc1-iNat1670795.ogg', 'strcuc1/iNat1165584.ogg': 'strcuc1-iNat1165584.ogg', 'strcuc1/iNat1490053.ogg': 'strcuc1-iNat1490053.ogg', 'strcuc1/iNat1465517.ogg': 'strcuc1-iNat1465517.ogg', 'strcuc1/iNat1367996.ogg': 'strcuc1-iNat1367996.ogg', 'strcuc1/iNat1347727.ogg': 'strcuc1-iNat1347727.ogg', 'strowl1/iNat1451619.ogg': 'strowl1-iNat1451619.ogg', 'strowl1/iNat1736437.ogg': 'strowl1-iNat1736437.ogg', 'strowl1/iNat1537360.ogg': 'strowl1-iNat1537360.ogg', 'swtman1/iNat1468159.ogg': 'swtman1-iNat1468159.ogg', 'swtman1/iNat841931.ogg': 'swtman1-iNat841931.ogg', 'swtman1/iNat980195.ogg': 'swtman1-iNat980195.ogg', 'swtman1/iNat1647280.ogg': 'swtman1-iNat1647280.ogg', 'swtman1/iNat1420444.ogg': 'swtman1-iNat1420444.ogg', 'swtman1/iNat1664402.ogg': 'swtman1-iNat1664402.ogg', 'swtman1/iNat1667664.ogg': 'swtman1-iNat1667664.ogg', 'tattin1/iNat1291008.ogg': 'tattin1-iNat1291008.ogg', 'thlwre1/iNat1446997.ogg': 'thlwre1-iNat1446997.ogg', 'thlwre1/iNat1540292.ogg': 'thlwre1-iNat1540292.ogg', 'toctou1/iNat1406213.ogg': 'toctou1-iNat1406213.ogg', 'trokin/iNat1543761.ogg': 'trokin-iNat1543761.ogg', 'trokin/iNat1088126.ogg': 'trokin-iNat1088126.ogg', 'trokin/iNat1631950.ogg': 'trokin-iNat1631950.ogg', 'trsowl/iNat1337876.ogg': 'trsowl-iNat1337876.ogg', 'trsowl/iNat1321621.ogg': 'trsowl-iNat1321621.ogg', 'trsowl/iNat1240859.ogg': 'trsowl-iNat1240859.ogg', 'trsowl/iNat1707373.ogg': 'trsowl-iNat1707373.ogg', 'trsowl/iNat1608858.ogg': 'trsowl-iNat1608858.ogg', 'varant1/iNat1227614.ogg': 'varant1-iNat1227614.ogg', 'wfwduc1/iNat1679287.ogg': 'wfwduc1-iNat1679287.ogg', 'wfwduc1/iNat1487538.ogg': 'wfwduc1-iNat1487538.ogg', 'whbwar2/iNat763637.ogg': 'whbwar2-iNat763637.ogg', 'whiwoo1/iNat1594296.ogg': 'whiwoo1-iNat1594296.ogg', 'whnjay1/iNat1404548.ogg': 'whnjay1-iNat1404548.ogg', 'whnjay1/iNat1199393.ogg': 'whnjay1-iNat1199393.ogg', 'whnjay1/iNat771603.ogg': 'whnjay1-iNat771603.ogg', 'whnjay1/iNat1636518.ogg': 'whnjay1-iNat1636518.ogg', 'whnjay1/iNat1651360.ogg': 'whnjay1-iNat1651360.ogg', 'whtdov/iNat1536547.ogg': 'whtdov-iNat1536547.ogg', 'whtdov/iNat1594270.ogg': 'whtdov-iNat1594270.ogg', 'whtdov/iNat1598157.ogg': 'whtdov-iNat1598157.ogg', 'y00678/iNat1461732.ogg': 'y00678-iNat1461732.ogg', 'y00678/iNat1593494.ogg': 'y00678-iNat1593494.ogg', 'y00678/iNat1397691.ogg': 'y00678-iNat1397691.ogg', 'yebela1/iNat1593008.ogg': 'yebela1-iNat1593008.ogg', 'yebela1/iNat1479050.ogg': 'yebela1-iNat1479050.ogg', 'yebela1/iNat1521944.ogg': 'yebela1-iNat1521944.ogg', 'yecpar/iNat1360878.ogg': 'yecpar-iNat1360878.ogg', 'yecpar/iNat1347445.ogg': 'yecpar-iNat1347445.ogg', 'yehcar1/iNat1268927.ogg': 'yehcar1-iNat1268927.ogg', 'yehcar1/iNat585409.ogg': 'yehcar1-iNat585409.ogg', 'yehcar1/iNat1701473.ogg': 'yehcar1-iNat1701473.ogg'}
PATH_MAP = {'/home/salman/Documents/data/birdclef-2026/train_audio/stbwoo2/XC467895.ogg': '/home/salman/Documents/data/download_corrupt/stbwoo2-XC467895.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/1161364/iNat1264238.ogg': '/home/salman/Documents/data/download_corrupt/1161364-iNat1264238.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/209233/iNat1545859.ogg': '/home/salman/Documents/data/download_corrupt/209233-iNat1545859.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/22956/iNat1693371.ogg': '/home/salman/Documents/data/download_corrupt/22956-iNat1693371.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat781822.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat781822.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat1353836.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat1353836.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat1460521.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat1460521.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/22973/iNat1645288.ogg': '/home/salman/Documents/data/download_corrupt/22973-iNat1645288.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/23158/iNat1322093.ogg': '/home/salman/Documents/data/download_corrupt/23158-iNat1322093.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/24279/iNat1306335.ogg': '/home/salman/Documents/data/download_corrupt/24279-iNat1306335.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/24279/iNat1435402.ogg': '/home/salman/Documents/data/download_corrupt/24279-iNat1435402.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/244024/iNat1219059.ogg': '/home/salman/Documents/data/download_corrupt/244024-iNat1219059.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/244024/iNat1583846.ogg': '/home/salman/Documents/data/download_corrupt/244024-iNat1583846.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/244024/iNat1573678.ogg': '/home/salman/Documents/data/download_corrupt/244024-iNat1573678.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/25092/iNat1645314.ogg': '/home/salman/Documents/data/download_corrupt/25092-iNat1645314.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/326272/iNat1299066.ogg': '/home/salman/Documents/data/download_corrupt/326272-iNat1299066.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/326272/iNat1303382.ogg': '/home/salman/Documents/data/download_corrupt/326272-iNat1303382.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/43435/iNat1054872.ogg': '/home/salman/Documents/data/download_corrupt/43435-iNat1054872.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/43435/iNat1243480.ogg': '/home/salman/Documents/data/download_corrupt/43435-iNat1243480.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1717935.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1717935.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1346356.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1346356.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1346365.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1346365.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1317366.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1317366.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1559514.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1559514.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/47144/iNat1191939.ogg': '/home/salman/Documents/data/download_corrupt/47144-iNat1191939.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/476521/iNat1648597.ogg': '/home/salman/Documents/data/download_corrupt/476521-iNat1648597.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/555146/iNat1375734.ogg': '/home/salman/Documents/data/download_corrupt/555146-iNat1375734.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/555146/iNat1375753.ogg': '/home/salman/Documents/data/download_corrupt/555146-iNat1375753.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat1372639.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat1372639.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat924044.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat924044.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat924035.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat924035.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/65377/iNat1676955.ogg': '/home/salman/Documents/data/download_corrupt/65377-iNat1676955.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/67107/iNat1635719.ogg': '/home/salman/Documents/data/download_corrupt/67107-iNat1635719.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/ashgre1/iNat963674.ogg': '/home/salman/Documents/data/download_corrupt/ashgre1-iNat963674.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/ashgre1/iNat1400791.ogg': '/home/salman/Documents/data/download_corrupt/ashgre1-iNat1400791.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/baffal1/iNat1672327.ogg': '/home/salman/Documents/data/download_corrupt/baffal1-iNat1672327.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/baffal1/iNat1711622.ogg': '/home/salman/Documents/data/download_corrupt/baffal1-iNat1711622.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1638891.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1638891.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1302882.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1302882.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1371833.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1371833.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat335243.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat335243.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1631602.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1631602.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1496209.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1496209.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/banana/iNat1630115.ogg': '/home/salman/Documents/data/download_corrupt/banana-iNat1630115.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat1654575.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat1654575.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat1418545.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat1418545.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat1738725.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat1738725.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/barant1/iNat76423.ogg': '/home/salman/Documents/data/download_corrupt/barant1-iNat76423.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat851301.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat851301.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat851302.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat851302.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat851299.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat851299.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat1275000.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat1275000.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat1517987.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat1517987.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/batbel1/iNat1710152.ogg': '/home/salman/Documents/data/download_corrupt/batbel1-iNat1710152.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/baymac/iNat1304419.ogg': '/home/salman/Documents/data/download_corrupt/baymac-iNat1304419.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/baymac/iNat976078.ogg': '/home/salman/Documents/data/download_corrupt/baymac-iNat976078.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1318531.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1318531.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat942901.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat942901.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1294916.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1294916.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1338852.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1338852.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1499546.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1499546.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1352566.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1352566.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1543298.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1543298.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1683874.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1683874.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1580446.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1580446.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat418728.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat418728.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat797291.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat797291.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat950353.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat950353.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1333153.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1333153.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat594163.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat594163.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1520789.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1520789.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bbwduc/iNat1705504.ogg': '/home/salman/Documents/data/download_corrupt/bbwduc-iNat1705504.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bkcdon/iNat1637377.ogg': '/home/salman/Documents/data/download_corrupt/bkcdon-iNat1637377.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bkcdon/iNat1396398.ogg': '/home/salman/Documents/data/download_corrupt/bkcdon-iNat1396398.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bkhpar/iNat1637590.ogg': '/home/salman/Documents/data/download_corrupt/bkhpar-iNat1637590.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bkhpar/iNat1029272.ogg': '/home/salman/Documents/data/download_corrupt/bkhpar-iNat1029272.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/blheag1/iNat1675853.ogg': '/home/salman/Documents/data/download_corrupt/blheag1-iNat1675853.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/blheag1/iNat953708.ogg': '/home/salman/Documents/data/download_corrupt/blheag1-iNat953708.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1422961.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1422961.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1406256.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1406256.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1457501.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1457501.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bncfly/iNat1554596.ogg': '/home/salman/Documents/data/download_corrupt/bncfly-iNat1554596.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1691483.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1691483.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1200017.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1200017.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1556528.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1556528.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bobfly1/iNat1487398.ogg': '/home/salman/Documents/data/download_corrupt/bobfly1-iNat1487398.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brcmar1/iNat1730049.ogg': '/home/salman/Documents/data/download_corrupt/brcmar1-iNat1730049.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brcmar1/iNat1658256.ogg': '/home/salman/Documents/data/download_corrupt/brcmar1-iNat1658256.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brcmar1/iNat1737157.ogg': '/home/salman/Documents/data/download_corrupt/brcmar1-iNat1737157.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1480534.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1480534.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1706506.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1706506.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1610861.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1610861.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat514729.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat514729.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1491227.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1491227.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1659173.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1659173.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1309637.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1309637.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1548013.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1548013.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1050844.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1050844.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/brnowl/iNat1491232.ogg': '/home/salman/Documents/data/download_corrupt/brnowl-iNat1491232.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bufpar/iNat1295642.ogg': '/home/salman/Documents/data/download_corrupt/bufpar-iNat1295642.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/bufpar/iNat1299514.ogg': '/home/salman/Documents/data/download_corrupt/bufpar-iNat1299514.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/burowl/iNat1589934.ogg': '/home/salman/Documents/data/download_corrupt/burowl-iNat1589934.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/camfli1/iNat1336230.ogg': '/home/salman/Documents/data/download_corrupt/camfli1-iNat1336230.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat228765.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat228765.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat1428711.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat1428711.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat1424302.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat1424302.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/chobla1/iNat1540294.ogg': '/home/salman/Documents/data/download_corrupt/chobla1-iNat1540294.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat1710475.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat1710475.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat782270.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat782270.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat905814.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat905814.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat826415.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat826415.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat1167591.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat1167591.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat1637929.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat1637929.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat782291.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat782291.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/coffal1/iNat395438.ogg': '/home/salman/Documents/data/download_corrupt/coffal1-iNat395438.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1591339.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1591339.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat946279.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat946279.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1599244.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1599244.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1672503.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1672503.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1268738.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1268738.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1623767.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1623767.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1321681.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1321681.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compau/iNat1294212.ogg': '/home/salman/Documents/data/download_corrupt/compau-iNat1294212.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compot1/iNat1668960.ogg': '/home/salman/Documents/data/download_corrupt/compot1-iNat1668960.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/compot1/iNat1660624.ogg': '/home/salman/Documents/data/download_corrupt/compot1-iNat1660624.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1693777.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1693777.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1684518.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1684518.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1678524.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1678524.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/crbthr1/iNat1277382.ogg': '/home/salman/Documents/data/download_corrupt/crbthr1-iNat1277382.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/epaori4/iNat1592245.ogg': '/home/salman/Documents/data/download_corrupt/epaori4-iNat1592245.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/epaori4/iNat649978.ogg': '/home/salman/Documents/data/download_corrupt/epaori4-iNat649978.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/eulfly1/iNat1738901.ogg': '/home/salman/Documents/data/download_corrupt/eulfly1-iNat1738901.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1711295.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1711295.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1664968.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1664968.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1308138.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1308138.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1738605.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1738605.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1240485.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1240485.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1335628.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1335628.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fepowl/iNat1287848.ogg': '/home/salman/Documents/data/download_corrupt/fepowl-iNat1287848.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fotfly/iNat1193130.ogg': '/home/salman/Documents/data/download_corrupt/fotfly-iNat1193130.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/fusfly1/iNat1518620.ogg': '/home/salman/Documents/data/download_corrupt/fusfly1-iNat1518620.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/giwrai1/iNat1673888.ogg': '/home/salman/Documents/data/download_corrupt/giwrai1-iNat1673888.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/giwrai1/iNat1349850.ogg': '/home/salman/Documents/data/download_corrupt/giwrai1-iNat1349850.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grasal3/iNat1632581.ogg': '/home/salman/Documents/data/download_corrupt/grasal3-iNat1632581.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grasal3/iNat1644284.ogg': '/home/salman/Documents/data/download_corrupt/grasal3-iNat1644284.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grasal3/iNat1614411.ogg': '/home/salman/Documents/data/download_corrupt/grasal3-iNat1614411.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greant1/iNat1635481.ogg': '/home/salman/Documents/data/download_corrupt/greant1-iNat1635481.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greant1/iNat1508328.ogg': '/home/salman/Documents/data/download_corrupt/greant1-iNat1508328.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greant1/iNat936816.ogg': '/home/salman/Documents/data/download_corrupt/greant1-iNat936816.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greela/iNat1231355.ogg': '/home/salman/Documents/data/download_corrupt/greela-iNat1231355.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1690035.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1690035.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1572002.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1572002.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1209312.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1209312.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1663561.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1663561.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1400476.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1400476.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1623199.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1623199.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1391832.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1391832.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grekis/iNat1667823.ogg': '/home/salman/Documents/data/download_corrupt/grekis-iNat1667823.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1381842.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1381842.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1375792.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1375792.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1375793.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1375793.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1350689.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1350689.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1370909.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1370909.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1638552.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1638552.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat952416.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat952416.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1350614.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1350614.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/greyel/iNat1303954.ogg': '/home/salman/Documents/data/download_corrupt/greyel-iNat1303954.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grfdov1/iNat1395710.ogg': '/home/salman/Documents/data/download_corrupt/grfdov1-iNat1395710.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/grfdov1/iNat1400824.ogg': '/home/salman/Documents/data/download_corrupt/grfdov1-iNat1400824.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1537449.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1537449.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1288203.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1288203.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1596768.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1596768.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat816375.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat816375.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1255088.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1255088.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1594836.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1594836.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1378299.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1378299.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1346486.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1346486.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1620374.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1620374.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1569899.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1569899.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1624903.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1624903.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1577300.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1577300.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1724472.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1724472.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/gycwor1/iNat1683695.ogg': '/home/salman/Documents/data/download_corrupt/gycwor1-iNat1683695.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1666148.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1666148.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1409352.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1409352.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1364301.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1364301.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1551547.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1551547.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat935753.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat935753.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1397767.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1397767.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1512573.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1512573.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1362595.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1362595.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1417357.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1417357.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1321989.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1321989.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat409684.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat409684.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1304457.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1304457.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1569993.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1569993.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1731791.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1731791.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1316764.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1316764.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/houspa/iNat1358970.ogg': '/home/salman/Documents/data/download_corrupt/houspa-iNat1358970.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/limpki/iNat1319758.ogg': '/home/salman/Documents/data/download_corrupt/limpki-iNat1319758.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/limpki/iNat1320813.ogg': '/home/salman/Documents/data/download_corrupt/limpki-iNat1320813.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/limpki/iNat1072786.ogg': '/home/salman/Documents/data/download_corrupt/limpki-iNat1072786.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/linwoo1/iNat1302630.ogg': '/home/salman/Documents/data/download_corrupt/linwoo1-iNat1302630.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/linwoo1/iNat1535721.ogg': '/home/salman/Documents/data/download_corrupt/linwoo1-iNat1535721.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/linwoo1/iNat1371736.ogg': '/home/salman/Documents/data/download_corrupt/linwoo1-iNat1371736.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/mabpar/iNat1626097.ogg': '/home/salman/Documents/data/download_corrupt/mabpar-iNat1626097.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/masgna1/iNat1635487.ogg': '/home/salman/Documents/data/download_corrupt/masgna1-iNat1635487.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/oliwoo1/iNat1346713.ogg': '/home/salman/Documents/data/download_corrupt/oliwoo1-iNat1346713.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1687083.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1687083.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1355177.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1355177.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1503877.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1503877.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1657675.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1657675.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/orwpar/iNat1079708.ogg': '/home/salman/Documents/data/download_corrupt/orwpar-iNat1079708.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat226664.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat226664.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1398129.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1398129.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1595562.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1595562.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1370949.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1370949.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1692289.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1692289.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1556374.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1556374.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1004549.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1004549.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1670343.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1670343.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat288776.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat288776.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat482127.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat482127.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1135797.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1135797.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1697529.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1697529.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1359848.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1359848.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/osprey/iNat1361039.ogg': '/home/salman/Documents/data/download_corrupt/osprey-iNat1361039.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1709147.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1709147.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1418628.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1418628.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1418634.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1418634.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/paltan1/iNat1618415.ogg': '/home/salman/Documents/data/download_corrupt/paltan1-iNat1618415.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/picpig2/iNat1607749.ogg': '/home/salman/Documents/data/download_corrupt/picpig2-iNat1607749.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/pirfly1/iNat1635054.ogg': '/home/salman/Documents/data/download_corrupt/pirfly1-iNat1635054.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/pirfly1/iNat1677277.ogg': '/home/salman/Documents/data/download_corrupt/pirfly1-iNat1677277.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat911601.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat911601.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat1612345.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat1612345.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat1435256.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat1435256.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/plcjay1/iNat1435257.ogg': '/home/salman/Documents/data/download_corrupt/plcjay1-iNat1435257.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rebscy1/iNat1324031.ogg': '/home/salman/Documents/data/download_corrupt/rebscy1-iNat1324031.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/redjun/iNat1661079.ogg': '/home/salman/Documents/data/download_corrupt/redjun-iNat1661079.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/redjun/iNat1681112.ogg': '/home/salman/Documents/data/download_corrupt/redjun-iNat1681112.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/redjun/iNat953958.ogg': '/home/salman/Documents/data/download_corrupt/redjun-iNat953958.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/relser1/iNat1557442.ogg': '/home/salman/Documents/data/download_corrupt/relser1-iNat1557442.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/relser1/iNat1370757.ogg': '/home/salman/Documents/data/download_corrupt/relser1-iNat1370757.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/relser1/iNat1344314.ogg': '/home/salman/Documents/data/download_corrupt/relser1-iNat1344314.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/roahaw/iNat1677378.ogg': '/home/salman/Documents/data/download_corrupt/roahaw-iNat1677378.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/roahaw/iNat1458636.ogg': '/home/salman/Documents/data/download_corrupt/roahaw-iNat1458636.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat870811.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat870811.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1684073.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1684073.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat852442.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat852442.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1682587.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1682587.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1672514.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1672514.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat546228.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat546228.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat850316.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat850316.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1707784.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1707784.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1615216.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1615216.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat851551.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat851551.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1691551.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1691551.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rubthr1/iNat1691430.ogg': '/home/salman/Documents/data/download_corrupt/rubthr1-iNat1691430.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rufnig1/iNat1657250.ogg': '/home/salman/Documents/data/download_corrupt/rufnig1-iNat1657250.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/rumfly1/iNat1734627.ogg': '/home/salman/Documents/data/download_corrupt/rumfly1-iNat1734627.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/ruther1/iNat1483642.ogg': '/home/salman/Documents/data/download_corrupt/ruther1-iNat1483642.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1692175.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1692175.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1313823.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1313823.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1300076.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1300076.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1300148.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1300148.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1667770.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1667770.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saffin/iNat1449859.ogg': '/home/salman/Documents/data/download_corrupt/saffin-iNat1449859.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/saytan1/iNat1677185.ogg': '/home/salman/Documents/data/download_corrupt/saytan1-iNat1677185.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/scadov1/iNat1299298.ogg': '/home/salman/Documents/data/download_corrupt/scadov1-iNat1299298.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/scadov1/iNat1491465.ogg': '/home/salman/Documents/data/download_corrupt/scadov1-iNat1491465.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/scadov1/iNat1276971.ogg': '/home/salman/Documents/data/download_corrupt/scadov1-iNat1276971.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/schpar1/iNat1293642.ogg': '/home/salman/Documents/data/download_corrupt/schpar1-iNat1293642.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1321023.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1321023.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1532661.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1532661.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1345739.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1345739.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shcfly1/iNat1471076.ogg': '/home/salman/Documents/data/download_corrupt/shcfly1-iNat1471076.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shshaw/iNat1590156.ogg': '/home/salman/Documents/data/download_corrupt/shshaw-iNat1590156.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shshaw/iNat1602640.ogg': '/home/salman/Documents/data/download_corrupt/shshaw-iNat1602640.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat869228.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat869228.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat870997.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat870997.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat870998.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat870998.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/shtnig1/iNat1696713.ogg': '/home/salman/Documents/data/download_corrupt/shtnig1-iNat1696713.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sibtan2/iNat1402979.ogg': '/home/salman/Documents/data/download_corrupt/sibtan2-iNat1402979.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/smbani/iNat915724.ogg': '/home/salman/Documents/data/download_corrupt/smbani-iNat915724.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/smbani/iNat1594767.ogg': '/home/salman/Documents/data/download_corrupt/smbani-iNat1594767.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/smbtin1/iNat1734628.ogg': '/home/salman/Documents/data/download_corrupt/smbtin1-iNat1734628.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/smbtin1/iNat81751.ogg': '/home/salman/Documents/data/download_corrupt/smbtin1-iNat81751.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sobcac1/iNat1387094.ogg': '/home/salman/Documents/data/download_corrupt/sobcac1-iNat1387094.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sobcac1/iNat1432132.ogg': '/home/salman/Documents/data/download_corrupt/sobcac1-iNat1432132.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sobtyr1/iNat1718955.ogg': '/home/salman/Documents/data/download_corrupt/sobtyr1-iNat1718955.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sobtyr1/iNat1355327.ogg': '/home/salman/Documents/data/download_corrupt/sobtyr1-iNat1355327.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1701203.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1701203.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1685298.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1685298.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1705430.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1705430.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1687317.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1687317.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat1181651.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat1181651.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat671916.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat671916.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/socfly1/iNat797558.ogg': '/home/salman/Documents/data/download_corrupt/socfly1-iNat797558.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sofspi1/iNat1664377.ogg': '/home/salman/Documents/data/download_corrupt/sofspi1-iNat1664377.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/sofspi1/iNat1510202.ogg': '/home/salman/Documents/data/download_corrupt/sofspi1-iNat1510202.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1203529.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1203529.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1405995.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1405995.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1637171.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1637171.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1637169.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1637169.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1685486.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1685486.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/soulap1/iNat1434604.ogg': '/home/salman/Documents/data/download_corrupt/soulap1-iNat1434604.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/souscr1/iNat1244955.ogg': '/home/salman/Documents/data/download_corrupt/souscr1-iNat1244955.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/spbant3/iNat1695874.ogg': '/home/salman/Documents/data/download_corrupt/spbant3-iNat1695874.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/spispi1/iNat1503058.ogg': '/home/salman/Documents/data/download_corrupt/spispi1-iNat1503058.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/spispi1/iNat1374076.ogg': '/home/salman/Documents/data/download_corrupt/spispi1-iNat1374076.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/spispi1/iNat1456192.ogg': '/home/salman/Documents/data/download_corrupt/spispi1-iNat1456192.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/squcuc1/iNat1358561.ogg': '/home/salman/Documents/data/download_corrupt/squcuc1-iNat1358561.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/squcuc1/iNat1358573.ogg': '/home/salman/Documents/data/download_corrupt/squcuc1-iNat1358573.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/squcuc1/iNat188319.ogg': '/home/salman/Documents/data/download_corrupt/squcuc1-iNat188319.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1691050.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1691050.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1675976.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1675976.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1665191.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1665191.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1670795.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1670795.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1165584.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1165584.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1490053.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1490053.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1465517.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1465517.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1367996.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1367996.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strcuc1/iNat1347727.ogg': '/home/salman/Documents/data/download_corrupt/strcuc1-iNat1347727.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strowl1/iNat1451619.ogg': '/home/salman/Documents/data/download_corrupt/strowl1-iNat1451619.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strowl1/iNat1736437.ogg': '/home/salman/Documents/data/download_corrupt/strowl1-iNat1736437.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/strowl1/iNat1537360.ogg': '/home/salman/Documents/data/download_corrupt/strowl1-iNat1537360.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1468159.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1468159.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat841931.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat841931.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat980195.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat980195.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1647280.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1647280.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1420444.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1420444.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1664402.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1664402.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/swtman1/iNat1667664.ogg': '/home/salman/Documents/data/download_corrupt/swtman1-iNat1667664.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/tattin1/iNat1291008.ogg': '/home/salman/Documents/data/download_corrupt/tattin1-iNat1291008.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/thlwre1/iNat1446997.ogg': '/home/salman/Documents/data/download_corrupt/thlwre1-iNat1446997.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/thlwre1/iNat1540292.ogg': '/home/salman/Documents/data/download_corrupt/thlwre1-iNat1540292.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/toctou1/iNat1406213.ogg': '/home/salman/Documents/data/download_corrupt/toctou1-iNat1406213.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trokin/iNat1543761.ogg': '/home/salman/Documents/data/download_corrupt/trokin-iNat1543761.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trokin/iNat1088126.ogg': '/home/salman/Documents/data/download_corrupt/trokin-iNat1088126.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trokin/iNat1631950.ogg': '/home/salman/Documents/data/download_corrupt/trokin-iNat1631950.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1337876.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1337876.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1321621.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1321621.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1240859.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1240859.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1707373.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1707373.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/trsowl/iNat1608858.ogg': '/home/salman/Documents/data/download_corrupt/trsowl-iNat1608858.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/varant1/iNat1227614.ogg': '/home/salman/Documents/data/download_corrupt/varant1-iNat1227614.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/wfwduc1/iNat1679287.ogg': '/home/salman/Documents/data/download_corrupt/wfwduc1-iNat1679287.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/wfwduc1/iNat1487538.ogg': '/home/salman/Documents/data/download_corrupt/wfwduc1-iNat1487538.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whbwar2/iNat763637.ogg': '/home/salman/Documents/data/download_corrupt/whbwar2-iNat763637.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whiwoo1/iNat1594296.ogg': '/home/salman/Documents/data/download_corrupt/whiwoo1-iNat1594296.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1404548.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1404548.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1199393.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1199393.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat771603.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat771603.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1636518.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1636518.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whnjay1/iNat1651360.ogg': '/home/salman/Documents/data/download_corrupt/whnjay1-iNat1651360.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whtdov/iNat1536547.ogg': '/home/salman/Documents/data/download_corrupt/whtdov-iNat1536547.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whtdov/iNat1594270.ogg': '/home/salman/Documents/data/download_corrupt/whtdov-iNat1594270.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/whtdov/iNat1598157.ogg': '/home/salman/Documents/data/download_corrupt/whtdov-iNat1598157.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/y00678/iNat1461732.ogg': '/home/salman/Documents/data/download_corrupt/y00678-iNat1461732.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/y00678/iNat1593494.ogg': '/home/salman/Documents/data/download_corrupt/y00678-iNat1593494.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/y00678/iNat1397691.ogg': '/home/salman/Documents/data/download_corrupt/y00678-iNat1397691.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yebela1/iNat1593008.ogg': '/home/salman/Documents/data/download_corrupt/yebela1-iNat1593008.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yebela1/iNat1479050.ogg': '/home/salman/Documents/data/download_corrupt/yebela1-iNat1479050.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yebela1/iNat1521944.ogg': '/home/salman/Documents/data/download_corrupt/yebela1-iNat1521944.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yecpar/iNat1360878.ogg': '/home/salman/Documents/data/download_corrupt/yecpar-iNat1360878.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yecpar/iNat1347445.ogg': '/home/salman/Documents/data/download_corrupt/yecpar-iNat1347445.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yehcar1/iNat1268927.ogg': '/home/salman/Documents/data/download_corrupt/yehcar1-iNat1268927.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yehcar1/iNat585409.ogg': '/home/salman/Documents/data/download_corrupt/yehcar1-iNat585409.ogg', '/home/salman/Documents/data/birdclef-2026/train_audio/yehcar1/iNat1701473.ogg': '/home/salman/Documents/data/download_corrupt/yehcar1-iNat1701473.ogg'}

In [3]:
# =========================
# Standard Library
# =========================
import os
import gc
import json
import time
import random
import copy
import warnings

# =========================
# Core Libraries
# =========================
import numpy as np
import pandas as pd

# =========================
# PyTorch
# =========================
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torch.optim import AdamW
from torch.utils.data.sampler import WeightedRandomSampler
from torch.cuda.amp import GradScaler
from torch.optim.lr_scheduler import CosineAnnealingLR
from torchvision import transforms
from torchvision.transforms import v2

# =========================
# Audio Processing
# =========================
import torchaudio
import torchaudio.transforms as T
import librosa
import librosa.display
import soundfile as sf

# =========================
# Image Processing
# =========================
import cv2
from PIL import Image
import albumentations as A
import matplotlib.pyplot as plt

# =========================
# Augmentations
# =========================
import audiomentations as AA

# =========================
# ML / CV Utilities
# =========================
import timm
import sklearn
from sklearn.model_selection import StratifiedKFold, StratifiedGroupKFold
from sklearn import metrics

# =========================
# Training Utilities
# =========================
from tqdm import tqdm
from timm.scheduler import CosineLRScheduler
from IPython.display import Audio

import random

from torch.optim.swa_utils import AveragedModel

/home/salman/Documents/codebases/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
def framewise_to_prediction(output, feat_time = 20, duration = 20, infer_duration = 5):
    inference_type = "overlap_average_max_delta"
    tta_delta = 2
    framewise_prob = output#.numpy()
    num_segments, num_labels, frames_per_segment = framewise_prob.shape
    
    step = int(feat_time * (infer_duration / duration))
    
    pad_frames = (frames_per_segment - step) // 2
    if (frames_per_segment - step) % 2 != 0:
        extra_pad = 1
    else:
        extra_pad = 0
    framewise_ss_len = frames_per_segment + step*(num_segments - 1)
    
    
    framewise_ss_preds = np.zeros((framewise_ss_len, num_segments, num_labels), dtype=np.float32)
    framewise_ss_preds_mask = np.zeros((framewise_ss_len, 1), dtype=np.float32)
    
    for segment_ind in range(num_segments):
        framewise_ss_preds[segment_ind*step: (segment_ind*step) + frames_per_segment, segment_ind] += framewise_prob[segment_ind].T
        framewise_ss_preds_mask[segment_ind*step: (segment_ind*step) + frames_per_segment] += 1
    
    if inference_type in ["overlap_average_max", "overlap_average_max_delta"]:
        framewise_ss_preds = framewise_ss_preds.sum(1)
        framewise_ss_preds = framewise_ss_preds / framewise_ss_preds_mask
        
    elif inference_type == "overlap_max":
        framewise_ss_preds = framewise_ss_preds.max(1)
    
    framewise_ss_preds = framewise_ss_preds[pad_frames:-pad_frames - extra_pad]
    segmentwise_preds = framewise_ss_preds.reshape(num_segments, step, num_labels).max(1)
    if inference_type == "overlap_average_max_delta": 
        segmentwise_preds *= 0.5
        for segment_ind in range(num_segments):
            if segment_ind == 0:
                segmentwise_preds[segment_ind] += framewise_ss_preds[segment_ind*step: (segment_ind+1)*step].max(0) * 0.25
            else:
                segmentwise_preds[segment_ind] += framewise_ss_preds[segment_ind*step - tta_delta: (segment_ind+1)*step - tta_delta].max(0) * 0.25
    
            if segment_ind == (num_segments -1):
                segmentwise_preds[segment_ind] += framewise_ss_preds[segment_ind*step: (segment_ind+1)*step].max(0) * 0.25
            else:
                segmentwise_preds[segment_ind] += framewise_ss_preds[segment_ind*step + tta_delta: (segment_ind+1)*step + tta_delta].max(0) * 0.25

    return segmentwise_preds


def framewise_to_prediction_whole(output, feat_time = 20, duration = 20, infer_duration = 5):
    inference_type = "overlap_average_max_delta"
    tta_delta = 2
    framewise_prob = output#.numpy()
    num_segments, num_labels, frames_per_segment = framewise_prob.shape
    
    step = int(feat_time * (infer_duration / duration))
    
    pad_frames = (frames_per_segment - step) // 2
    if (frames_per_segment - step) % 2 != 0:
        extra_pad = 1
    else:
        extra_pad = 0
    framewise_ss_len = frames_per_segment + step*(num_segments - 1)
    
    
    framewise_ss_preds = np.zeros((framewise_ss_len, num_segments, num_labels), dtype=np.float32)
    framewise_ss_preds_mask = np.zeros((framewise_ss_len, 1), dtype=np.float32)
    
    for segment_ind in range(num_segments):
        framewise_ss_preds[segment_ind*step: (segment_ind*step) + frames_per_segment, segment_ind] += framewise_prob[segment_ind].T
        framewise_ss_preds_mask[segment_ind*step: (segment_ind*step) + frames_per_segment] += 1
    
    if inference_type in ["overlap_average_max", "overlap_average_max_delta"]:
        framewise_ss_preds = framewise_ss_preds.sum(1)
        framewise_ss_preds = framewise_ss_preds / framewise_ss_preds_mask
        
    elif inference_type == "overlap_max":
        framewise_ss_preds = framewise_ss_preds.max(1)
    
    framewise_ss_preds = framewise_ss_preds[pad_frames:-pad_frames - extra_pad]
    return framewise_ss_preds

In [5]:
class Config:
    sample_rate = 32000
    melspec_parameters = {
        "n_mels" : 448,
        "n_fft" : 4096, 
        "hop_length" : 1001,
        "win_length" : 4096,
        "f_min" : 0,
        "f_max" : 16000,
        "sample_rate" : sample_rate,
        "normalized" : True,
        "aug" : {
            "apply" : True,
            "freq_mask_param" : 30, 
            "time_mask_param" : 20, 
            "num_masks" : 2
        }
    }

    s0b0ns = {
        "n_mels" : melspec_parameters.get("n_mels"),
        "smoothings" : [1, 3], #1 means main input
        "backbone": "tf_efficientnet_b0_ns",
        "pretrained": False,
        "in_chans" : 3,
        "num_classes" : len(label2num),
        "forward_drop_rate" : 0.5,
        "attn_heads" : {
            "insecta" : len(class_idx_mapping['Insecta'])+1,
            "amph" : len(class_idx_mapping['Amphibia'])+2,
            "mam" : len(class_idx_mapping['Mammalia'])+2,
            "aves" : len(class_idx_mapping['Aves'])+1,
        }
    }



    s1b0ns = {
        "n_mels" : melspec_parameters.get("n_mels"),
        "smoothings" : [1, 3], #1 means main input
        "backbone": "tf_efficientnet_b0_ns",
        "pretrained": False,
        "in_chans" : 3,
        "num_classes" : len(label2num),
        "forward_drop_rate" : 0.5,
        "attn_heads" : {
            "insecta" : len(class_idx_mapping['Insecta'])+1,
            "amph" : len(class_idx_mapping['Amphibia'])+2,
            "mam" : len(class_idx_mapping['Mammalia'])+2,
            "aves" : len(class_idx_mapping['Aves'])+1,
        }
    }


    s2b0ns = {
        "n_mels" : melspec_parameters.get("n_mels"),
        "smoothings" : [1, 3], #1 means main input
        "backbone": "tf_efficientnet_b0_ns",
        "pretrained": False,
        "in_chans" : 3,
        "num_classes" : len(label2num),
        "forward_drop_rate" : 0.5,
        "attn_heads" : {
            "insecta" : len(class_idx_mapping['Insecta'])+1,
            "amph" : len(class_idx_mapping['Amphibia'])+2,
            "mam" : len(class_idx_mapping['Mammalia'])+2,
            "aves" : len(class_idx_mapping['Aves'])+1,
        }
    }

    
    s2b1ns = {
        "n_mels" : melspec_parameters.get("n_mels"),
        "smoothings" : [1, 3], #1 means main input
        "backbone": "tf_efficientnet_b1_ns",
        "pretrained": False,
        "in_chans" : 3,
        "num_classes" : len(label2num),
        "forward_drop_rate" : 0.5,
        "attn_heads" : {
            "insecta" : len(class_idx_mapping['Insecta'])+1,
            "amph" : len(class_idx_mapping['Amphibia'])+2,
            "mam" : len(class_idx_mapping['Mammalia'])+2,
            "aves" : len(class_idx_mapping['Aves'])+1,
        }
    }

    s2b2ns = {
        "n_mels" : melspec_parameters.get("n_mels"),
        "smoothings" : [1, 3], #1 means main input
        "backbone": "tf_efficientnet_b2_ns",
        "pretrained": False,
        "in_chans" : 3,
        "num_classes" : len(label2num),
        "forward_drop_rate" : 0.5,
        "attn_heads" : {
            "insecta" : len(class_idx_mapping['Insecta'])+1,
            "amph" : len(class_idx_mapping['Amphibia'])+2,
            "mam" : len(class_idx_mapping['Mammalia'])+2,
            "aves" : len(class_idx_mapping['Aves'])+1,
        }
    }

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import timm


def init_layer(layer):
    nn.init.xavier_uniform_(layer.weight)
    if hasattr(layer, "bias"):
        if layer.bias is not None:
            layer.bias.data.fill_(0.)

def init_bn(bn):
    bn.bias.data.fill_(0.)
    bn.weight.data.fill_(1.0)

def init_weights(model):
    classname = model.__class__.__name__
    if classname.find("Conv2d") != -1:
        nn.init.xavier_uniform_(model.weight, gain=np.sqrt(2))
        model.bias.data.fill_(0)
    elif classname.find("BatchNorm") != -1:
        model.weight.data.normal_(1.0, 0.02)
        model.bias.data.fill_(0)
    elif classname.find("GRU") != -1:
        for weight in model.parameters():
            if len(weight.size()) > 1:
                nn.init.orthogonal_(weight.data)
    elif classname.find("Linear") != -1:
        model.weight.data.normal_(0, 0.01)
        model.bias.data.zero_()

def pad_framewise_output(framewise_output, frames_num):
    output = F.interpolate(
        framewise_output.unsqueeze(1),
        size=(frames_num, framewise_output.size(2)),
        align_corners=True,
        mode="bilinear").squeeze(1)

    return output

class AttBlock(nn.Module):
    def __init__(self,
                 in_features: int,
                 out_features: int,
                 activation="linear",
                 multiplier = 1,
                 temperature=1.0):
        super().__init__()


        self.fc1 = nn.Linear(in_features * multiplier, in_features, bias=True)
        self.activation = activation
        self.temperature = temperature
        self.att = nn.Conv1d(
            in_channels=in_features,
            out_channels=out_features,
            kernel_size=1,
            stride=1,
            padding=0,
            bias=True)
        self.cla = nn.Conv1d(
            in_channels=in_features,
            out_channels=out_features,
            kernel_size=1,
            stride=1,
            padding=0,
            bias=True)

        self.bn_att = nn.BatchNorm1d(out_features)
        self.init_weights()

    def init_weights(self):
        init_layer(self.att)
        init_layer(self.cla)
        init_bn(self.bn_att)
        init_layer(self.fc1)

    def forward(self, x, forward_drop_rate):
        x = F.relu_(self.fc1(x))
        x = x.transpose(1, 2)
        x = F.dropout(x, p=forward_drop_rate, training=self.training)
        # x: (n_samples, n_in, n_time)
        norm_att = torch.softmax(torch.clamp(self.att(x), -10, 10), dim=-1)
        cla = self.nonlinear_transform(self.cla(x))
        x = torch.sum(norm_att * cla, dim=2)
        return x, cla

    def nonlinear_transform(self, x):
        if self.activation == 'linear':
            return x
        elif self.activation == 'sigmoid':
            return torch.sigmoid(x)


def get_encoder(model_parameters):
    base_model = timm.create_model(
        model_parameters.get("backbone"),
        pretrained=model_parameters.get("pretrained"),
        in_chans=model_parameters.get("in_chans"),
    )
    layers = list(base_model.children())[:-2]
    encoder = nn.Sequential(*layers)
    in_features = base_model.num_features
    return encoder, in_features


class BaseSEDModel(nn.Module):
    def __init__(self, model_parameters):
        super().__init__()
        self.forward_drop_rate = model_parameters.get("forward_drop_rate")
        self.bn0 = nn.BatchNorm2d(model_parameters.get("n_mels"))

        self.encoder, in_features = get_encoder(model_parameters)

        self.smoothings = model_parameters.get("smoothings")
        
        multiplier = len(self.smoothings)
        print ("Multiplier", multiplier)

        attn_heads = model_parameters.get("attn_heads")
        self.attn_head_names = list(attn_heads.keys())

        attn_head_layers = {}
        for each in self.attn_head_names:
            attn_head_layers[each] = AttBlock(in_features, attn_heads.get(each), activation="linear", multiplier=multiplier)
        self.attn_head_layers = nn.ModuleDict(attn_head_layers)

        self.init_weight()

    def init_weight(self):
        init_bn(self.bn0)

    def smooth_time(self, x, kernel_size):
        if kernel_size == 1:
            x = F.dropout(x, p=self.forward_drop_rate, training=self.training)
            x = x.transpose(1, 2)
        else:
            padding = (kernel_size - 1) // 2
            x1 = F.max_pool1d(x, kernel_size=kernel_size, stride=1, padding=padding)
            x2 = F.avg_pool1d(x, kernel_size=kernel_size, stride=1, padding=padding)
            x = x1 + x2
            x = F.dropout(x, p=self.forward_drop_rate, training=self.training)
            x = x.transpose(1, 2)
        return x

    def forward(self, x):
        x = x.transpose(1, 2)
        x = self.bn0(x)
        x = x.transpose(1, 2)

        x = self.encoder(x)
        
        x = torch.mean(x, dim=2) #BS X C X TIME

        if len(self.smoothings) == 1 and self.smoothings[0] == 1:
            features = self.smooth_time(x, 1)
        else:
            features = []
            for i in self.smoothings:
                features.append(self.smooth_time(x, i))
            features = torch.cat(features, dim=2)
        
        #BS X TIME X C*Multiplier

        outputs = {}
        for attn_head_name in self.attn_head_names:
            clip, frame = self.attn_head_layers[attn_head_name](features, self.forward_drop_rate)
            outputs[attn_head_name] = {
                "clip" : clip,
                "frame" : frame
            }

        return outputs


class MelSpectrogramTransform(nn.Module):
    def __init__(self, melspec_config, top_db, eps=1e-6,):
        super().__init__()

        melspec_config = melspec_config.copy()
        aug = melspec_config.pop("aug")
        self.eps = eps
        self.top_db = top_db
        self.mel = T.MelSpectrogram(**melspec_config)
        self.db = T.AmplitudeToDB(stype="power", top_db=top_db)
        
        self.freq_mask = T.FrequencyMasking(freq_mask_param=aug["freq_mask_param"], iid_masks=True)
        self.time_mask = T.TimeMasking(time_mask_param=aug["time_mask_param"], iid_masks=True)
        self.num_masks = aug["num_masks"]

    @torch.no_grad()
    def forward(self, waveforms):
        X = self.db(self.mel(waveforms))
        mean = X.mean((1, 2), keepdim=True)
        std = X.std((1, 2), keepdim=True)
        Xstd = (X - mean) / (std + self.eps)
        norm_max = torch.amax(Xstd, dim=(1, 2), keepdim=True)
        norm_min = torch.amin(Xstd, dim=(1, 2), keepdim=True)
        X = (Xstd - norm_min) / (norm_max - norm_min + self.eps)

        if self.training:
            for _ in range(self.num_masks):
                X = self.freq_mask(X)
                X = self.time_mask(X)

        return X

class SEDModel(nn.Module):
    def __init__(self, model_parameters, melspec_config):
        super().__init__()
        self.base_sed = BaseSEDModel(model_parameters)
        self.transform_ = MelSpectrogramTransform(melspec_config, top_db=80)

    
    @torch.no_grad()
    def transform(self, x):
        x = self.transform_(x).unsqueeze(1)
        x = torch.cat([x, x, x], dim=1)
        return x

    
    def forward(self, x):
        output = self.base_sed(x)
        output = torch.cat([output["aves"]["frame"][:, :-1], output["insecta"]["frame"][:, :-1], output["amph"]["frame"][:, :-1], output["mam"]["frame"][:, :-1]], dim=1)
        return output.sigmoid()

In [7]:
insects_idx = class_idx_mapping['Insecta'].copy()
amph_idx = class_idx_mapping['Amphibia'].copy()
mam_idx = class_idx_mapping['Mammalia'].copy()
aves_idx = class_idx_mapping['Aves'].copy()

In [8]:
models = {
    "s0b0ns" : SEDModel(Config.s0b0ns, Config.melspec_parameters),
    "s1b0ns" : SEDModel(Config.s1b0ns, Config.melspec_parameters),
    "s2b0ns" : SEDModel(Config.s2b0ns, Config.melspec_parameters),
    "s2b1ns" : SEDModel(Config.s2b1ns, Config.melspec_parameters),
    "s2b2ns" : SEDModel(Config.s2b2ns, Config.melspec_parameters),
}

/home/salman/Documents/codebases/venv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name tf_efficientnet_b0_ns to current tf_efficientnet_b0.ns_jft_in1k.
  model = create_fn(

Multiplier 2
Multiplier 2
Multiplier 2

/home/salman/Documents/codebases/venv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name tf_efficientnet_b1_ns to current tf_efficientnet_b1.ns_jft_in1k.
  model = create_fn(
/home/salman/Documents/codebases/venv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name tf_efficientnet_b2_ns to current tf_efficientnet_b2.ns_jft_in1k.
  model = create_fn(

Multiplier 2
Multiplier 2

In [9]:
model_paths = {
    "s0b0ns" : "../stage0/outputs/stage0_b0ns/stage0_b0ns_final.pt",
    "s1b0ns" : "../stage1/outputs/stage1_b0ns_v2/stage1_b0ns_v2_final.pt",
    "s2b0ns" : "../stage2/outputs/stage2_b0ns_v2/stage2_b0ns_v2_final.pt",
    "s2b1ns" : "../stage2/outputs/stage2_b1ns_v2/stage2_b1ns_v2_final.pt",
    "s2b2ns" : "../stage2/outputs/stage2_b2ns_v2/stage2_b2ns_v2_final.pt",
}

In [10]:
transform_mel = MelSpectrogramTransform(Config.melspec_parameters.copy(), top_db=80).cuda()
def transform_mel_fn(x):
    with torch.no_grad():
        x = transform_mel(x).unsqueeze(1)
        x = torch.cat([x, x, x], dim=1)
    return x

In [11]:
for key in model_paths.keys():
    print (key)
    state_dict = torch.load(model_paths[key], map_location='cpu')
    models[key].load_state_dict(state_dict)
    models[key].transform_ = nn.Identity()
    models[key].eval()
    models[key].to('cuda')

s0b0ns
s1b0ns
s2b0ns
s2b1ns
s2b2ns

In [12]:
model_names = list(model_paths.keys())
print (model_names), len(model_names)

['s0b0ns', 's1b0ns', 's2b0ns', 's2b1ns', 's2b2ns']

(None, 5)

In [13]:
def predict(x):
    outputs_c = 0
    outputs_whole = 0
    with torch.no_grad():
        x = x.cuda()
        x = transform_mel_fn(x)
        for key in model_names:
            p = models[key](x).detach().cpu()
            p = p.numpy()
            p_c = framewise_to_prediction(p.copy(), feat_time = 20, duration = 20, infer_duration = 5).astype(np.float32)
            p_w = framewise_to_prediction_whole(p.copy(), feat_time = 20, duration = 20, infer_duration = 5).astype(np.float32)
            outputs_c += p_c
            outputs_whole += p_w
            
    return outputs_c / len(model_names), outputs_whole / len(model_names)

In [14]:
def prepare_wave(wave):
    sr = 32000
    chunk_duration = 5
    context_duration = 7.5

    max_len = 60 * 32000
    if wave.shape[0] > max_len:
        wave = wave[:max_len]
    elif wave.shape[0] <= (3 * 32000):
        return [], False
    else:
        pad_len = max_len - wave.shape[0]
        wave = np.pad(wave, (0, pad_len), mode='constant')

    pad_samples = int(context_duration * sr)
    step_samples = int(chunk_duration * sr)
    total_samples = int((chunk_duration + 2 * context_duration) * sr)

    sig = wave
    sig_padded = np.pad(sig, (pad_samples, pad_samples), mode='constant')

    chunks = []
    for i in range(0, len(sig), step_samples):
        chunk = sig_padded[i : i + total_samples]
        max_v = np.max(np.abs(chunk))
        if max_v > 0:
            chunk = chunk / max_v
        chunks.append(chunk)
    chunks = np.stack(chunks)
    return chunks, True

In [15]:
train_soundscapes_dir = "/home/salman/Documents/codebases/ADD_DATA_XC_SITE/outputs_ogg"
train_soundscapes = os.listdir(train_soundscapes_dir)
print (len(train_soundscapes))

23454

In [16]:
PREDICTIONS_DIR = "predictions_xc_1"
os.makedirs(PREDICTIONS_DIR, exist_ok=True)

In [17]:
sum_c , sum_w = [], []
fp_c, fp_w = [], []
ss_fp = []
for i, ss in tqdm(enumerate(train_soundscapes), total=len(train_soundscapes)):
    fp = os.path.join(train_soundscapes_dir, ss)
    try:
        wave, rate = librosa.load(fp, sr=32000, res_type='kaiser_best')
    except:
        continue
    wave, valid = prepare_wave(wave)
    if not valid:
        print (i)
        continue
    
    ss_fp.append(fp)
    pred = predict(torch.tensor(wave, dtype=torch.float32))
    pred_c, pred_w = pred
    sum_p_c = float(np.sum(np.max(pred_c, axis=0)))
    sum_p_w = float(np.sum(np.max(pred_w, axis=0)))
    sum_c.append(sum_p_c)
    sum_w.append(sum_p_w)
    
    np_namec = ".".join(ss.replace("/", "-").split(".")[:-1]) + "_c.npy"
    np.save(os.path.join(PREDICTIONS_DIR, np_namec), pred_c)

    np_namew = ".".join(ss.replace("/", "-").split(".")[:-1]) + "_w.npy"
    np.save(os.path.join(PREDICTIONS_DIR, np_namew), pred_w)

    fp_c.append(np_namec)
    fp_w.append(np_namew)

  0%|          | 61/23454 [00:11<51:10,  7.62it/s]

59

  0%|          | 86/23454 [00:16<53:24,  7.29it/s]

84

  1%|▏         | 309/23454 [00:58<51:11,  7.54it/s]

307

  1%|▏         | 316/23454 [00:59<54:05,  7.13it/s]

314

  1%|▏         | 347/23454 [01:05<54:45,  7.03it/s]

345

  2%|▏         | 354/23454 [01:06<50:55,  7.56it/s]

352

  2%|▏         | 361/23454 [01:07<51:54,  7.42it/s]

359

  2%|▏         | 395/23454 [01:13<56:06,  6.85it/s]

393

  2%|▏         | 526/23454 [01:36<1:03:06,  6.06it/s]/tmp/ipykernel_978048/3724797377.py:7: UserWarning: PySoundFile failed. Trying audioread instead.
  wave, rate = librosa.load(fp, sr=32000, res_type='kaiser_best')
/home/salman/Documents/codebases/venv/lib/python3.12/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
  2%|▏         | 536/23454 [01:38<53:40,  7.12it/s]

534

  2%|▏         | 584/23454 [01:47<1:13:23,  5.19it/s]

584

  3%|▎         | 639/23454 [01:57<54:21,  7.00it/s]

637

  3%|▎         | 790/23454 [02:26<1:03:20,  5.96it/s]

788

  4%|▎         | 843/23454 [02:36<54:55,  6.86it/s]

841

  4%|▍         | 883/23454 [02:43<49:21,  7.62it/s]

881

  4%|▍         | 930/23454 [02:52<59:02,  6.36it/s]

928

  5%|▍         | 1060/23454 [03:17<54:38,  6.83it/s]

1058

  5%|▍         | 1114/23454 [03:27<56:29,  6.59it/s]

1112

  5%|▍         | 1131/23454 [03:30<51:59,  7.16it/s]

1129

  5%|▍         | 1168/23454 [03:37<1:16:50,  4.83it/s]

1168

  5%|▌         | 1181/23454 [03:39<53:09,  6.98it/s]

1179

  5%|▌         | 1254/23454 [03:53<40:59,  9.03it/s]

1251
1252

  5%|▌         | 1276/23454 [03:56<44:22,  8.33it/s]

1273
1274

  6%|▌         | 1358/23454 [04:12<52:18,  7.04it/s]

1356

  6%|▌         | 1386/23454 [04:17<58:44,  6.26it/s]

1384

  6%|▌         | 1393/23454 [04:18<52:58,  6.94it/s]

1391

  6%|▌         | 1443/23454 [04:28<52:31,  6.98it/s]

1441

  7%|▋         | 1634/23454 [05:07<53:50,  6.75it/s]

1632

  7%|▋         | 1640/23454 [05:08<47:38,  7.63it/s]

1638

  7%|▋         | 1676/23454 [05:15<59:09,  6.14it/s]

1674

  8%|▊         | 1798/23454 [05:38<54:50,  6.58it/s]

1796

  8%|▊         | 1810/23454 [05:40<49:11,  7.33it/s]

1808

  8%|▊         | 1864/23454 [05:50<50:44,  7.09it/s]

1862

  9%|▊         | 2013/23454 [06:19<49:30,  7.22it/s]

2011

  9%|▉         | 2159/23454 [06:47<1:01:30,  5.77it/s]

2159

 10%|▉         | 2272/23454 [07:08<51:07,  6.91it/s]

2270

 10%|█         | 2431/23454 [07:39<1:10:15,  4.99it/s]

2431

 10%|█         | 2446/23454 [07:41<1:09:48,  5.02it/s]

2446

 11%|█         | 2525/23454 [07:56<49:30,  7.04it/s]

2523

 11%|█         | 2604/23454 [08:10<46:27,  7.48it/s]

2602

 12%|█▏        | 2809/23454 [08:48<1:04:58,  5.30it/s]

2809

 12%|█▏        | 2835/23454 [08:53<45:14,  7.60it/s]

2833

 12%|█▏        | 2840/23454 [08:53<42:21,  8.11it/s]

2838

 12%|█▏        | 2899/23454 [09:05<47:46,  7.17it/s]

2897

 13%|█▎        | 2974/23454 [09:20<1:01:31,  5.55it/s]

2974

 13%|█▎        | 3033/23454 [09:31<48:17,  7.05it/s]

3031

 13%|█▎        | 3152/23454 [09:53<48:28,  6.98it/s]

3150

 14%|█▍        | 3272/23454 [10:16<45:51,  7.33it/s]

3270
3272

 14%|█▍        | 3314/23454 [10:23<48:51,  6.87it/s]

3312

 14%|█▍        | 3361/23454 [10:32<1:01:11,  5.47it/s]

3361

 15%|█▍        | 3460/23454 [10:52<50:40,  6.58it/s]

3458

 15%|█▌        | 3631/23454 [11:25<1:05:33,  5.04it/s]

3631

 16%|█▌        | 3782/23454 [11:53<44:51,  7.31it/s]

3780

 16%|█▋        | 3832/23454 [12:03<59:02,  5.54it/s]

3832

 16%|█▋        | 3848/23454 [12:05<44:13,  7.39it/s]

3846

 17%|█▋        | 3895/23454 [12:14<44:02,  7.40it/s]

3893

 17%|█▋        | 3950/23454 [12:24<48:23,  6.72it/s]

3948

 17%|█▋        | 3964/23454 [12:26<41:06,  7.90it/s]

3961
3962

 17%|█▋        | 3976/23454 [12:29<1:03:39,  5.10it/s]

3976

 17%|█▋        | 4013/23454 [12:35<45:36,  7.10it/s]

4011

 17%|█▋        | 4047/23454 [12:41<46:29,  6.96it/s]

4045

 18%|█▊        | 4119/23454 [12:55<59:41,  5.40it/s]

4119

 18%|█▊        | 4173/23454 [13:05<44:53,  7.16it/s]

4171

 18%|█▊        | 4241/23454 [13:18<47:24,  6.76it/s]

4239

 18%|█▊        | 4280/23454 [13:26<1:01:28,  5.20it/s]

4278

 18%|█▊        | 4286/23454 [13:27<45:50,  6.97it/s]

4284

 18%|█▊        | 4320/23454 [13:33<58:25,  5.46it/s]

4320

 19%|█▊        | 4387/23454 [13:45<47:59,  6.62it/s]

4385

 19%|█▉        | 4465/23454 [14:00<44:58,  7.04it/s]

4463

 19%|█▉        | 4537/23454 [14:14<43:47,  7.20it/s]

4535

 20%|██        | 4750/23454 [14:54<44:27,  7.01it/s]

4748

 20%|██        | 4807/23454 [15:05<41:58,  7.40it/s]

4805

 21%|██        | 4824/23454 [15:08<54:34,  5.69it/s]

4824

 21%|██        | 4834/23454 [15:10<53:53,  5.76it/s]

4834

 21%|██        | 4875/23454 [15:17<42:14,  7.33it/s]

4873

 21%|██        | 4981/23454 [15:39<53:05,  5.80it/s]

4981

 22%|██▏       | 5080/23454 [15:58<53:59,  5.67it/s]

5078

 22%|██▏       | 5087/23454 [15:59<49:56,  6.13it/s]

5085

 22%|██▏       | 5101/23454 [16:02<46:04,  6.64it/s]

5099

 22%|██▏       | 5153/23454 [16:12<50:40,  6.02it/s]

5151

 22%|██▏       | 5216/23454 [16:23<43:24,  7.00it/s]

5214

 23%|██▎       | 5298/23454 [16:39<46:44,  6.48it/s]

5296

 24%|██▍       | 5712/23454 [17:58<56:56,  5.19it/s]

5712

 24%|██▍       | 5722/23454 [18:00<43:16,  6.83it/s]

5720

 25%|██▌       | 5978/23454 [18:49<42:26,  6.86it/s]

5976

 26%|██▌       | 6048/23454 [19:01<40:15,  7.21it/s]

6046

 26%|██▌       | 6131/23454 [19:17<50:20,  5.74it/s]

6129

 27%|██▋       | 6232/23454 [19:36<44:53,  6.39it/s]

6230

 27%|██▋       | 6256/23454 [19:40<43:12,  6.63it/s]

6254

 27%|██▋       | 6389/23454 [20:06<36:58,  7.69it/s]

6387

 27%|██▋       | 6427/23454 [20:13<38:37,  7.35it/s]

6425

 27%|██▋       | 6441/23454 [20:15<39:06,  7.25it/s]

6439

 27%|██▋       | 6444/23454 [20:15<33:56,  8.35it/s]

6442

 28%|██▊       | 6456/23454 [20:17<38:15,  7.41it/s]

6454

 28%|██▊       | 6562/23454 [20:37<38:07,  7.39it/s]

6560

 28%|██▊       | 6681/23454 [20:59<38:54,  7.19it/s]

6679

 29%|██▉       | 6864/23454 [21:34<37:53,  7.30it/s]

6862

 30%|██▉       | 7025/23454 [22:04<41:22,  6.62it/s]

7023

 30%|███       | 7110/23454 [22:22<45:50,  5.94it/s]

7108

 30%|███       | 7132/23454 [22:26<39:38,  6.86it/s]

7130

 31%|███       | 7213/23454 [22:42<40:39,  6.66it/s]

7211

 31%|███       | 7256/23454 [22:49<29:41,  9.09it/s]

7253
7254

 31%|███       | 7327/23454 [23:03<36:02,  7.46it/s]

7325

 32%|███▏      | 7426/23454 [23:22<37:42,  7.08it/s]

7424

 32%|███▏      | 7437/23454 [23:24<47:22,  5.63it/s]

7437

 32%|███▏      | 7578/23454 [23:50<35:58,  7.35it/s]

7576

 32%|███▏      | 7584/23454 [23:51<36:26,  7.26it/s]

7582

 32%|███▏      | 7605/23454 [23:55<48:33,  5.44it/s]

7605

 32%|███▏      | 7615/23454 [23:56<35:27,  7.44it/s]

7613

 33%|███▎      | 7668/23454 [24:06<35:30,  7.41it/s]

7666

 33%|███▎      | 7780/23454 [24:27<36:10,  7.22it/s]

7778

 33%|███▎      | 7813/23454 [24:33<39:52,  6.54it/s]

7811

 34%|███▎      | 7895/23454 [24:49<45:18,  5.72it/s]

7895

 34%|███▍      | 7984/23454 [25:05<54:31,  4.73it/s]

7984

 34%|███▍      | 7989/23454 [25:06<51:25,  5.01it/s]

7989

 34%|███▍      | 7993/23454 [25:07<43:48,  5.88it/s]

7993

 34%|███▍      | 8049/23454 [25:18<47:31,  5.40it/s]

8049

 35%|███▍      | 8121/23454 [25:31<36:06,  7.08it/s]

8119

 35%|███▌      | 8294/23454 [26:04<33:32,  7.53it/s]

8292

 36%|███▌      | 8418/23454 [26:27<33:14,  7.54it/s]

8416

 36%|███▌      | 8479/23454 [26:38<37:14,  6.70it/s]

8477

 36%|███▌      | 8499/23454 [26:41<34:32,  7.22it/s]

8497

 36%|███▋      | 8509/23454 [26:43<34:53,  7.14it/s]

8507

 36%|███▋      | 8522/23454 [26:45<35:28,  7.02it/s]

8520

 36%|███▋      | 8560/23454 [26:52<42:57,  5.78it/s]

8560

 37%|███▋      | 8602/23454 [27:00<37:09,  6.66it/s]

8600

 37%|███▋      | 8645/23454 [27:08<35:42,  6.91it/s]

8643

 37%|███▋      | 8686/23454 [27:16<34:33,  7.12it/s]

8684

 37%|███▋      | 8692/23454 [27:17<37:30,  6.56it/s]

8690

 37%|███▋      | 8728/23454 [27:24<34:02,  7.21it/s]

8726

 38%|███▊      | 8821/23454 [27:41<36:02,  6.77it/s]

8819

 39%|███▊      | 9047/23454 [28:24<47:20,  5.07it/s]

9047

 39%|███▊      | 9061/23454 [28:26<39:18,  6.10it/s]

9059

 39%|███▊      | 9075/23454 [28:29<34:25,  6.96it/s]

9073

 39%|███▉      | 9142/23454 [28:41<32:03,  7.44it/s]

9140

 40%|███▉      | 9339/23454 [29:19<34:20,  6.85it/s]

9337

 40%|███▉      | 9342/23454 [29:19<30:06,  7.81it/s]

9340

 40%|███▉      | 9351/23454 [29:21<34:04,  6.90it/s]

9349

 40%|████      | 9400/23454 [29:30<43:12,  5.42it/s]

9400

 40%|████      | 9405/23454 [29:31<31:41,  7.39it/s]

9403

 40%|████      | 9427/23454 [29:35<36:01,  6.49it/s]

9425

 41%|████      | 9535/23454 [29:56<31:39,  7.33it/s]

9533

 41%|████      | 9605/23454 [30:09<33:31,  6.89it/s]

9603

 41%|████▏     | 9702/23454 [30:28<35:50,  6.40it/s]

9700

 42%|████▏     | 9740/23454 [30:35<32:19,  7.07it/s]

9738

 42%|████▏     | 9863/23454 [30:58<30:14,  7.49it/s]

9861

 42%|████▏     | 9871/23454 [31:00<32:23,  6.99it/s]

9869

 42%|████▏     | 9885/23454 [31:02<33:17,  6.79it/s]

9883

 42%|████▏     | 9896/23454 [31:04<33:12,  6.80it/s]

9894

 43%|████▎     | 10008/23454 [31:25<33:55,  6.61it/s]

10006

 43%|████▎     | 10076/23454 [31:37<30:55,  7.21it/s]

10074

 43%|████▎     | 10112/23454 [31:44<41:21,  5.38it/s]

10112

 44%|████▍     | 10284/23454 [32:16<42:26,  5.17it/s]

10284

 44%|████▍     | 10294/23454 [32:17<30:13,  7.25it/s]

10292

 44%|████▍     | 10393/23454 [32:35<28:30,  7.63it/s]

10391

 44%|████▍     | 10409/23454 [32:39<33:50,  6.43it/s]

10407

 45%|████▍     | 10499/23454 [32:56<32:54,  6.56it/s]

10497

 45%|████▍     | 10531/23454 [33:02<31:05,  6.93it/s]

10529

 45%|████▌     | 10556/23454 [33:06<29:57,  7.18it/s]

10554

 45%|████▌     | 10663/23454 [33:27<31:52,  6.69it/s]

10661

 46%|████▌     | 10764/23454 [33:45<23:13,  9.11it/s]

10761
10762

 46%|████▌     | 10834/23454 [33:59<1:05:13,  3.23it/s]

10834

 46%|████▋     | 10884/23454 [34:08<28:41,  7.30it/s]

10882

 47%|████▋     | 10940/23454 [34:17<28:15,  7.38it/s]

10938

 47%|████▋     | 10949/23454 [34:19<27:36,  7.55it/s]

10947

 47%|████▋     | 11058/23454 [34:40<31:17,  6.60it/s]

11056

 47%|████▋     | 11080/23454 [34:44<33:33,  6.14it/s]

11078

 47%|████▋     | 11133/23454 [34:54<27:18,  7.52it/s]

11131

 48%|████▊     | 11164/23454 [34:59<28:25,  7.21it/s]

11162

 48%|████▊     | 11324/23454 [35:29<26:54,  7.51it/s]

11322

 48%|████▊     | 11354/23454 [35:35<29:10,  6.91it/s]

11352

 49%|████▊     | 11394/23454 [35:42<28:22,  7.08it/s]

11392

 49%|████▊     | 11399/23454 [35:43<26:43,  7.52it/s]

11397

 49%|████▉     | 11536/23454 [36:09<26:58,  7.36it/s]

11534

 49%|████▉     | 11549/23454 [36:11<29:42,  6.68it/s]

11547

 49%|████▉     | 11600/23454 [36:21<28:45,  6.87it/s]

11598

 50%|████▉     | 11622/23454 [36:25<38:09,  5.17it/s]

11622

 50%|████▉     | 11626/23454 [36:25<26:42,  7.38it/s]

11624

 50%|████▉     | 11641/23454 [36:28<26:57,  7.31it/s]

11639

 50%|████▉     | 11670/23454 [36:33<35:16,  5.57it/s]

11670

 50%|█████     | 11727/23454 [36:44<27:19,  7.15it/s]

11725

 50%|█████     | 11839/23454 [37:05<26:19,  7.36it/s]

11837

 50%|█████     | 11844/23454 [37:05<28:42,  6.74it/s]

11842

 51%|█████     | 11994/23454 [37:35<35:29,  5.38it/s]

11994

 52%|█████▏    | 12086/23454 [37:52<26:39,  7.11it/s]

12084

 52%|█████▏    | 12164/23454 [38:08<25:20,  7.42it/s]

12162

 53%|█████▎    | 12547/23454 [39:20<27:16,  6.67it/s]

12545

 54%|█████▎    | 12596/23454 [39:29<24:30,  7.39it/s]

12594

 54%|█████▍    | 12608/23454 [39:31<24:47,  7.29it/s]

12606

 54%|█████▍    | 12690/23454 [39:46<25:57,  6.91it/s]

12688

 54%|█████▍    | 12712/23454 [39:50<26:01,  6.88it/s]

12710

 54%|█████▍    | 12779/23454 [40:02<30:18,  5.87it/s]

12779
12780

 55%|█████▍    | 12892/23454 [40:23<24:07,  7.30it/s]

12890

 56%|█████▌    | 13154/23454 [41:16<30:32,  5.62it/s]

13152

 56%|█████▋    | 13208/23454 [41:26<24:02,  7.10it/s]

13206

 56%|█████▋    | 13217/23454 [41:27<23:16,  7.33it/s]

13215

 56%|█████▋    | 13219/23454 [41:28<25:45,  6.62it/s]

13219

 56%|█████▋    | 13250/23454 [41:34<32:11,  5.28it/s]

13250

 57%|█████▋    | 13323/23454 [41:47<22:52,  7.38it/s]

13321

 57%|█████▋    | 13442/23454 [42:10<24:06,  6.92it/s]

13440

 58%|█████▊    | 13527/23454 [42:26<24:07,  6.86it/s]

13525

 58%|█████▊    | 13588/23454 [42:37<22:50,  7.20it/s]

13586

 58%|█████▊    | 13611/23454 [42:42<22:07,  7.42it/s]

13609

 58%|█████▊    | 13705/23454 [42:59<29:21,  5.53it/s]

13705

 59%|█████▊    | 13723/23454 [43:02<27:54,  5.81it/s]

13723

 59%|█████▊    | 13729/23454 [43:03<20:05,  8.07it/s]

13727

 59%|█████▊    | 13754/23454 [43:08<32:22,  4.99it/s]

13754

 59%|█████▉    | 13783/23454 [43:13<21:18,  7.56it/s]

13781

 59%|█████▉    | 13794/23454 [43:14<23:05,  6.97it/s]

13792

 59%|█████▉    | 13805/23454 [43:16<21:15,  7.57it/s]

13803

 59%|█████▉    | 13924/23454 [43:39<22:09,  7.17it/s]

13922

 60%|██████    | 14111/23454 [44:14<21:49,  7.14it/s]

14109

 60%|██████    | 14130/23454 [44:17<21:07,  7.35it/s]

14128

 60%|██████    | 14148/23454 [44:20<25:13,  6.15it/s]

14146

 61%|██████    | 14345/23454 [44:58<22:20,  6.79it/s]

14343

 62%|██████▏   | 14478/23454 [45:24<30:36,  4.89it/s]

14478

 62%|██████▏   | 14498/23454 [45:28<20:51,  7.16it/s]

14496

 62%|██████▏   | 14507/23454 [45:29<20:34,  7.25it/s]

14505

 62%|██████▏   | 14535/23454 [45:34<19:55,  7.46it/s]

14533

 62%|██████▏   | 14544/23454 [45:36<25:44,  5.77it/s]

14544

 62%|██████▏   | 14572/23454 [45:41<21:07,  7.01it/s]

14570

 62%|██████▏   | 14591/23454 [45:45<22:41,  6.51it/s]

14589
14591

 62%|██████▏   | 14652/23454 [45:56<21:03,  6.96it/s]

14650

 63%|██████▎   | 14704/23454 [46:05<19:08,  7.62it/s]

14702

 63%|██████▎   | 14819/23454 [46:26<21:29,  6.70it/s]

14817

 63%|██████▎   | 14837/23454 [46:30<21:12,  6.77it/s]

14835

 63%|██████▎   | 14860/23454 [46:34<22:31,  6.36it/s]

14858

 64%|██████▍   | 14964/23454 [46:53<15:24,  9.18it/s]

14961
14962

 64%|██████▍   | 15008/23454 [47:02<20:33,  6.85it/s]

15006

 65%|██████▍   | 15230/23454 [47:44<20:07,  6.81it/s]

15228

 65%|██████▌   | 15311/23454 [48:00<18:38,  7.28it/s]

15309

 66%|██████▌   | 15379/23454 [48:12<18:35,  7.24it/s]

15377

 66%|██████▌   | 15426/23454 [48:21<22:43,  5.89it/s]

15424

 66%|██████▌   | 15452/23454 [48:27<28:29,  4.68it/s]

15452

 66%|██████▌   | 15465/23454 [48:29<20:09,  6.61it/s]

15463

 67%|██████▋   | 15739/23454 [49:21<18:45,  6.86it/s]

15737

 67%|██████▋   | 15809/23454 [49:34<18:13,  6.99it/s]

15807

 68%|██████▊   | 15976/23454 [50:06<21:20,  5.84it/s]

15976

 68%|██████▊   | 16000/23454 [50:10<16:14,  7.65it/s]

15998

 69%|██████▊   | 16074/23454 [50:24<20:12,  6.09it/s]

16072

 69%|██████▊   | 16097/23454 [50:29<17:14,  7.11it/s]

16095

 69%|██████▉   | 16156/23454 [50:39<16:36,  7.32it/s]

16154

 69%|██████▉   | 16188/23454 [50:45<17:01,  7.11it/s]

16186

 70%|██████▉   | 16374/23454 [51:20<21:47,  5.41it/s]

16374

 70%|██████▉   | 16408/23454 [51:26<16:04,  7.30it/s]

16406

 70%|███████   | 16430/23454 [51:30<22:13,  5.27it/s]

16430

 70%|███████   | 16451/23454 [51:34<17:07,  6.82it/s]

16449

 70%|███████   | 16497/23454 [51:42<17:52,  6.49it/s]

16495

 71%|███████   | 16596/23454 [52:01<15:04,  7.58it/s]

16594

 71%|███████   | 16702/23454 [52:21<16:36,  6.78it/s]

16700

 72%|███████▏  | 16890/23454 [52:57<20:53,  5.23it/s]

16890

 72%|███████▏  | 16938/23454 [53:05<15:09,  7.17it/s]

16936

 72%|███████▏  | 16956/23454 [53:08<14:18,  7.57it/s]

16954

 72%|███████▏  | 16989/23454 [53:14<15:55,  6.76it/s]

16987

 73%|███████▎  | 17007/23454 [53:17<14:31,  7.39it/s]

17005

 73%|███████▎  | 17049/23454 [53:25<19:30,  5.47it/s]

17049

 73%|███████▎  | 17053/23454 [53:25<13:44,  7.77it/s]

17051

 73%|███████▎  | 17092/23454 [53:33<16:07,  6.58it/s]

17090

 73%|███████▎  | 17114/23454 [53:37<15:40,  6.74it/s]

17112

 73%|███████▎  | 17121/23454 [53:39<15:30,  6.81it/s]

17119

 73%|███████▎  | 17210/23454 [53:55<16:36,  6.27it/s]

17208

 73%|███████▎  | 17231/23454 [53:59<14:31,  7.14it/s]

17229

 74%|███████▍  | 17308/23454 [54:15<27:21,  3.74it/s]

17308

 75%|███████▍  | 17485/23454 [54:48<13:23,  7.43it/s]

17483

 75%|███████▍  | 17566/23454 [55:03<19:03,  5.15it/s]

17566

 75%|███████▌  | 17620/23454 [55:14<15:11,  6.40it/s]

17618

 75%|███████▌  | 17645/23454 [55:19<17:05,  5.66it/s]

17645

 76%|███████▌  | 17785/23454 [55:45<18:25,  5.13it/s]

17785

 76%|███████▌  | 17871/23454 [56:01<12:49,  7.25it/s]

17869

 76%|███████▋  | 17936/23454 [56:13<12:36,  7.30it/s]

17934

 77%|███████▋  | 17970/23454 [56:19<17:25,  5.24it/s]

17970

 77%|███████▋  | 18027/23454 [56:30<13:11,  6.85it/s]

18025

 77%|███████▋  | 18063/23454 [56:37<12:24,  7.24it/s]

18061

 77%|███████▋  | 18079/23454 [56:40<12:49,  6.98it/s]

18077

 77%|███████▋  | 18169/23454 [56:58<13:57,  6.31it/s]

18167

 78%|███████▊  | 18185/23454 [57:01<15:21,  5.72it/s]

18185

 78%|███████▊  | 18271/23454 [57:18<21:01,  4.11it/s]

18271

 78%|███████▊  | 18367/23454 [57:36<11:23,  7.45it/s]

18365

 79%|███████▉  | 18471/23454 [57:54<11:40,  7.11it/s]

18469

 79%|███████▉  | 18536/23454 [58:07<12:08,  6.75it/s]

18534

 79%|███████▉  | 18566/23454 [58:12<10:51,  7.50it/s]

18564

 79%|███████▉  | 18576/23454 [58:14<11:30,  7.07it/s]

18574

 79%|███████▉  | 18580/23454 [58:14<10:30,  7.73it/s]

18578

 79%|███████▉  | 18615/23454 [58:21<11:31,  7.00it/s]

18613

 79%|███████▉  | 18629/23454 [58:23<10:38,  7.55it/s]

18627

 80%|███████▉  | 18650/23454 [58:27<11:28,  6.97it/s]

18648

 80%|███████▉  | 18666/23454 [58:30<09:59,  7.99it/s]

18663
18664

 80%|███████▉  | 18759/23454 [58:46<10:36,  7.37it/s]

18757

 80%|████████  | 18814/23454 [58:56<11:15,  6.87it/s]

18812

 80%|████████  | 18835/23454 [59:00<12:43,  6.05it/s]

18833

 81%|████████  | 18981/23454 [59:28<15:53,  4.69it/s]

18981

 81%|████████  | 19007/23454 [59:33<10:54,  6.80it/s]

19005

 81%|████████  | 19018/23454 [59:35<10:04,  7.33it/s]

19016

 81%|████████  | 19047/23454 [59:40<13:05,  5.61it/s]

19047

 81%|████████  | 19055/23454 [59:41<10:08,  7.23it/s]

19053

 81%|████████▏ | 19091/23454 [59:48<09:48,  7.41it/s]

19089

 82%|████████▏ | 19125/23454 [59:54<10:05,  7.15it/s]

19123

 82%|████████▏ | 19173/23454 [1:00:04<10:27,  6.82it/s]

19171

 82%|████████▏ | 19291/23454 [1:00:26<09:56,  6.98it/s]

19289

 82%|████████▏ | 19331/23454 [1:00:33<10:15,  6.70it/s]

19329

 82%|████████▏ | 19349/23454 [1:00:36<10:31,  6.50it/s]

19347

 83%|████████▎ | 19414/23454 [1:00:48<09:48,  6.87it/s]

19412

 83%|████████▎ | 19462/23454 [1:00:57<09:19,  7.13it/s]

19460

 83%|████████▎ | 19500/23454 [1:01:04<08:56,  7.37it/s]

19498

 83%|████████▎ | 19509/23454 [1:01:06<12:29,  5.26it/s]

19509

 84%|████████▍ | 19655/23454 [1:01:34<11:00,  5.76it/s]

19655

 84%|████████▍ | 19686/23454 [1:01:40<08:48,  7.13it/s]

19684

 84%|████████▍ | 19701/23454 [1:01:42<08:09,  7.66it/s]

19699

 84%|████████▍ | 19805/23454 [1:02:02<08:14,  7.38it/s]

19803

 85%|████████▍ | 19840/23454 [1:02:09<10:55,  5.51it/s]

19840

 85%|████████▍ | 19906/23454 [1:02:20<07:53,  7.49it/s]

19904

 85%|████████▌ | 19957/23454 [1:02:30<08:21,  6.98it/s]

19955

 85%|████████▌ | 19980/23454 [1:02:34<08:08,  7.12it/s]

19978

 86%|████████▌ | 20063/23454 [1:02:50<07:41,  7.35it/s]

20061

 86%|████████▌ | 20220/23454 [1:03:18<07:45,  6.94it/s]

20218

 87%|████████▋ | 20329/23454 [1:03:39<06:56,  7.50it/s]

20327

 87%|████████▋ | 20353/23454 [1:03:43<08:51,  5.83it/s]

20353

 87%|████████▋ | 20466/23454 [1:04:05<07:09,  6.95it/s]

20464

 87%|████████▋ | 20472/23454 [1:04:06<06:39,  7.46it/s]

20470

 88%|████████▊ | 20527/23454 [1:04:16<07:06,  6.87it/s]

20525

 88%|████████▊ | 20593/23454 [1:04:28<06:36,  7.22it/s]

20591
20593

 88%|████████▊ | 20635/23454 [1:04:38<07:16,  6.45it/s]

20633

 88%|████████▊ | 20756/23454 [1:05:01<09:21,  4.80it/s]

20756

 89%|████████▉ | 20863/23454 [1:05:22<07:50,  5.51it/s]

20863

 89%|████████▉ | 20970/23454 [1:05:42<05:27,  7.58it/s]

20968

 90%|████████▉ | 21027/23454 [1:05:55<06:38,  6.09it/s]

21025

 90%|████████▉ | 21033/23454 [1:05:56<05:32,  7.29it/s]

21031

 90%|█████████ | 21114/23454 [1:06:11<06:20,  6.15it/s]

21112

 90%|█████████ | 21207/23454 [1:06:28<05:36,  6.68it/s]

21205

 90%|█████████ | 21219/23454 [1:06:30<04:54,  7.58it/s]

21217

 91%|█████████ | 21274/23454 [1:06:40<05:19,  6.82it/s]

21272

 91%|█████████ | 21311/23454 [1:06:46<04:56,  7.22it/s]

21309

 91%|█████████▏| 21452/23454 [1:07:12<04:38,  7.20it/s]

21450

 92%|█████████▏| 21506/23454 [1:07:23<04:25,  7.33it/s]

21504

 92%|█████████▏| 21565/23454 [1:07:34<04:45,  6.62it/s]

21563

 92%|█████████▏| 21636/23454 [1:07:47<04:15,  7.12it/s]

21634

 93%|█████████▎| 21702/23454 [1:07:59<03:59,  7.32it/s]

21700

 93%|█████████▎| 21758/23454 [1:08:09<05:21,  5.27it/s]

21758

 93%|█████████▎| 21825/23454 [1:08:21<03:54,  6.93it/s]

21823

 93%|█████████▎| 21837/23454 [1:08:23<03:33,  7.59it/s]

21835

 93%|█████████▎| 21872/23454 [1:08:29<03:42,  7.11it/s]

21870

 93%|█████████▎| 21917/23454 [1:08:37<03:52,  6.60it/s]

21915

 93%|█████████▎| 21922/23454 [1:08:38<03:25,  7.47it/s]

21920

 94%|█████████▎| 21959/23454 [1:08:45<03:17,  7.59it/s]

21957

 94%|█████████▎| 21966/23454 [1:08:46<05:04,  4.88it/s]

21966

 94%|█████████▍| 22030/23454 [1:08:58<03:39,  6.49it/s]

22028

 94%|█████████▍| 22099/23454 [1:09:12<03:20,  6.75it/s]

22097

 94%|█████████▍| 22103/23454 [1:09:12<03:06,  7.25it/s]

22101

 94%|█████████▍| 22118/23454 [1:09:15<03:57,  5.63it/s]

22118

 94%|█████████▍| 22124/23454 [1:09:16<03:16,  6.77it/s]

22122

 94%|█████████▍| 22131/23454 [1:09:17<02:52,  7.68it/s]

22129
22131

 95%|█████████▍| 22204/23454 [1:09:30<02:54,  7.16it/s]

22202

 95%|█████████▍| 22219/23454 [1:09:33<02:53,  7.11it/s]

22217

 95%|█████████▍| 22243/23454 [1:09:37<02:46,  7.28it/s]

22241

 95%|█████████▌| 22301/23454 [1:09:47<02:44,  7.02it/s]

22299

 95%|█████████▌| 22346/23454 [1:09:56<04:31,  4.09it/s]

22346

 95%|█████████▌| 22360/23454 [1:09:58<02:28,  7.39it/s]

22358

 96%|█████████▌| 22469/23454 [1:10:18<02:20,  7.02it/s]

22467

 96%|█████████▌| 22498/23454 [1:10:23<02:03,  7.74it/s]

22496

 96%|█████████▋| 22624/23454 [1:10:47<01:57,  7.08it/s]

22622

 97%|█████████▋| 22670/23454 [1:10:55<01:45,  7.44it/s]

22668

 97%|█████████▋| 22693/23454 [1:10:59<01:50,  6.89it/s]

22691

 97%|█████████▋| 22707/23454 [1:11:02<01:46,  7.01it/s]

22705

 97%|█████████▋| 22720/23454 [1:11:04<01:42,  7.17it/s]

22718

 97%|█████████▋| 22729/23454 [1:11:05<01:39,  7.29it/s]

22727

 97%|█████████▋| 22739/23454 [1:11:07<01:42,  6.97it/s]

22737

 97%|█████████▋| 22780/23454 [1:11:15<01:34,  7.11it/s]

22778

 97%|█████████▋| 22801/23454 [1:11:18<01:55,  5.66it/s]

22801

 97%|█████████▋| 22865/23454 [1:11:30<01:27,  6.70it/s]

22863

 98%|█████████▊| 23025/23454 [1:12:00<01:01,  6.94it/s]

23023

 99%|█████████▊| 23122/23454 [1:12:19<00:44,  7.44it/s]

23120

 99%|█████████▊| 23159/23454 [1:12:26<00:47,  6.16it/s]

23157

 99%|█████████▉| 23193/23454 [1:12:32<00:59,  4.35it/s]

23193

 99%|█████████▉| 23237/23454 [1:12:41<00:31,  6.90it/s]

23235

 99%|█████████▉| 23296/23454 [1:12:53<00:49,  3.22it/s]

23294

100%|█████████▉| 23377/23454 [1:13:09<00:10,  7.27it/s]

23375

100%|██████████| 23454/23454 [1:13:24<00:00,  5.33it/s]

In [18]:
df = pd.DataFrame()
df["ss_fp"] = ss_fp
df["fp_c"] = fp_c
df["fp_w"] = fp_w
df["sum_c"] = sum_c
df["sum_w"] = sum_w
df.head()

,ss_fp,fp_c,fp_w,sum_c,sum_w
0,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC73450 - Chestnut-vented Conebill - Conirostr...,XC73450 - Chestnut-vented Conebill - Conirostr...,6.051548,6.410594
1,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC493262 - Pheasant Cuckoo - Dromococcyx phasi...,XC493262 - Pheasant Cuckoo - Dromococcyx phasi...,3.266064,3.246703
2,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC1031747 - Roadside Hawk - Rupornis magnirost...,XC1031747 - Roadside Hawk - Rupornis magnirost...,3.593490,3.574535
3,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC709435 - Undulated Tinamou - Crypturellus un...,XC709435 - Undulated Tinamou - Crypturellus un...,3.962202,4.180517
4,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC699644 - Crested Caracara - Caracara plancus...,XC699644 - Crested Caracara - Caracara plancus...,6.700768,7.253014

In [19]:
df.to_csv(os.path.join(PREDICTIONS_DIR, "prediction_xc.csv"), index=False)

In [20]:
AV, IN, AM, MAM = [], [], [], []
for i, row in df.iterrows():
    ps = np.load(os.path.join(PREDICTIONS_DIR, row["fp_w"]))
    aves = ps[:, 0:162]
    insects = ps[:, 162:162+28]
    amph = ps[:, 162+28:162+28+36]
    mam = ps[:, 162+28+36:162+28+36+9]

    av = float(np.round(aves.max(axis=0), 2).sum())
    inn = float(np.round(insects.max(axis=0), 2).sum())
    am = float(np.round(amph.max(axis=0), 2).sum())
    ma = float(np.round(mam.max(axis=0), 2).sum())

    AV.append(av)
    IN.append(inn)
    AM.append(am)
    MAM.append(ma)

In [21]:
df["aves_sum"] = AV
df["insects_sum"] = IN
df["amph_sum"] = AM
df["mam_sum"] = MAM
df.head()

,ss_fp,fp_c,fp_w,sum_c,sum_w,aves_sum,insects_sum,amph_sum,mam_sum
0,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC73450 - Chestnut-vented Conebill - Conirostr...,XC73450 - Chestnut-vented Conebill - Conirostr...,6.051548,6.410594,6.280000,0.01,0.06,0.01
1,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC493262 - Pheasant Cuckoo - Dromococcyx phasi...,XC493262 - Pheasant Cuckoo - Dromococcyx phasi...,3.266064,3.246703,3.090000,0.00,0.00,0.04
2,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC1031747 - Roadside Hawk - Rupornis magnirost...,XC1031747 - Roadside Hawk - Rupornis magnirost...,3.593490,3.574535,3.470000,0.00,0.00,0.00
3,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC709435 - Undulated Tinamou - Crypturellus un...,XC709435 - Undulated Tinamou - Crypturellus un...,3.962202,4.180517,4.039999,0.03,0.00,0.00
4,/home/salman/Documents/codebases/ADD_DATA_XC_S...,XC699644 - Crested Caracara - Caracara plancus...,XC699644 - Crested Caracara - Caracara plancus...,6.700768,7.253014,7.050000,0.01,0.01,0.14

In [22]:
df.to_csv(os.path.join(PREDICTIONS_DIR, "prediction_xc_sp.csv"), index=False)

In [25]:
col = "aves_sum"
df[col].min(), df[col].max(), df[col].std(), df[col].mean()

(np.float64(0.0),
 np.float64(17.889999389648438),
 np.float64(2.5405334211775217),
 np.float64(5.217491760870384))

In [24]:
col = "insects_sum"
df[col].min(), df[col].max(), df[col].std(), df[col].mean()

(np.float64(0.0),
 np.float64(6.090000152587891),
 np.float64(0.18845710519499395),
 np.float64(0.05786039351854928))

In [23]:
col = "amph_sum"
df[col].min(), df[col].max(), df[col].std(), df[col].mean()

(np.float64(0.0),
 np.float64(5.189999580383301),
 np.float64(0.15715051285664178),
 np.float64(0.029300237853712358))

In [26]:
col = "mam_sum"
df[col].min(), df[col].max(), df[col].std(), df[col].mean()

(np.float64(0.0),
 np.float64(1.809999942779541),
 np.float64(0.06704213278231984),
 np.float64(0.022805549264351483))

In [37]:
np.round(insects.max(axis=0), 2)

array([0.  , 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  ], dtype=float32)

In [36]:
0.7**(1/0.55)

0.5228294863132033

In [40]:
fps = []
nps = []
for i, ss in tqdm(enumerate(train_soundscapes), total=len(train_soundscapes)):
    fp = os.path.join(data_dir, "train_soundscapes", ss)
    fps.append(fp)
    np_name = ".".join(ss.replace("/", "-").split(".")[:-1]) + ".npy"
    nps.append(np_name)

100%|██████████| 10658/10658 [00:00<00:00, 1306261.82it/s]

In [41]:
df = pd.DataFrame()
df["fp"] = fps
df["np"] = nps
df["sums"] = sums
df.head()

,fp,np,sums
0,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_3371_S02_20220330_231500.npy,84.153648
1,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_7147_S22_20211008_211500.npy,154.923355
2,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_1441_S01_20230416_191500.npy,79.370880
3,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_0173_S07_20141005_030400.npy,68.018127
4,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_10563_S17_20250606_000000.npy,112.578888

In [42]:
df.to_csv(os.path.join(PREDICTIONS_DIR, "prediction_ss.csv"), index=False)

In [43]:
train_soundscapes_df = pd.read_csv(os.path.join(data_dir, "train_soundscapes_labels.csv"))
train_soundscapes_df = train_soundscapes_df.drop_duplicates().reset_index(drop=True)

In [48]:
train_soundscapes_df['fp'] = "/home/salman/Documents/data/birdclef-2026/train_soundscapes/" + train_soundscapes_df['filename']

In [56]:
ignore_ss = []
for soundscape_fp in train_soundscapes_df['fp'].unique():
    sub_df = train_soundscapes_df[train_soundscapes_df['fp'] == soundscape_fp]
    if sub_df.shape[0] == 12:
        ignore_ss.append(soundscape_fp)
print (len(ignore_ss))

59

In [64]:
df1 = df[~df['fp'].isin(ignore_ss)].reset_index(drop=True)

In [65]:
df.shape, df1.shape

((10658, 3), (10599, 3))

In [66]:
df1.to_csv(os.path.join(PREDICTIONS_DIR, "prediction_ss_ignored.csv"), index=False)

In [67]:
df1

,fp,np,sums
0,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_3371_S02_20220330_231500.npy,84.153648
1,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_7147_S22_20211008_211500.npy,154.923355
2,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_1441_S01_20230416_191500.npy,79.370880
3,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_0173_S07_20141005_030400.npy,68.018127
4,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_10563_S17_20250606_000000.npy,112.578888
...,...,...,...
10594,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_1777_S01_20231026_203000.npy,67.087013
10595,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_5287_S13_20211109_210000.npy,82.385757
10596,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_6351_S13_20230402_001500.npy,71.079399
10597,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_5501_S13_20220402_023000.npy,21.109703
10598,/home/salman/Documents/data/birdclef-2026/trai...,BC2026_Train_8575_S22_20221205_193000.npy,259.822815

In [68]:
pred.shape

(60, 235)